ActiveLearningStudio/ActiveLearningStudio-API

database/migrations/2020_08_26_160652_create_h5p_libraries_table.php, database/migrations/2020_08_26_161102_create_h5p_contents_table.php, database/migrations/2020_08_26_162836_create_h5p_tags_table.php, database/migrations/2020_08_26_163546_create_h5p_events_table.php, database/migrations/2020_08_26_163746_create_h5p_event_logs_table.php, database/migrations/2020_08_26_163905_create_h5p_counters_table.php, database/migrations/2020_08_26_183710_create_h5p_libraries_hub_cache_table.php
Please review h5p migration. I have included columns that are in MySQL. Also rearranged columns as we have in MySQL.
=> h5p migraitons update

H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php, app/Http/Controllers/Api/V1/H5pController.php, config/laravel-h5p.php, routes/api.php
H5P embed route and updates for develop
=> H5P embed route and updates for develop

routes/api.php
=> h5p libraries route update

H5P/laravel-h5p/src/LaravelH5p/Eloquents/H5pContent.php, H5P/laravel-h5p/src/LaravelH5p/Eloquents/H5pLibrary.php, app/Http/Resources/V1/ActivityResource.php, app/Models/Activity.php, routes/api.php
I have added some logic to Activity Resource to have additional parameters. I will be pull out logic and added to controller action in coming commits.
=> Update for edit activity in playlist

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Resources/V1/H5pActivityResource.php, routes/api.php
Support H5P into Activity Controller for Preview
=> Support H5P into Activity Controller for Preview

app/CurrikiGo/Canvas/Playlist.php
=> Fixed a resource path in Playlist class file.

H5P/laravel-h5p/routes/laravel-h5p.php, routes/api.php
H5P Export duplicate route fixed
=> H5P Export duplicate route fixed

app/CurrikiGo/Moodle/Course.php, app/CurrikiGo/Moodle/Playlist.php, app/Http/Controllers/Api/V1/CurrikiGo/CourseController.php, app/Http/Controllers/Api/V1/CurrikiGo/PublishController.php, routes/api.php
CurrikiGo - It publish playlists to Moodle. It also fetch Course from moodle related to a project.
=> CurrikiGo - Publish to Moodle

app/Http/Controllers/Api/V1/ProjectController.php, app/Repositories/Project/ProjectRepository.php, routes/api.php
=> project load shared endpoint

app/Repositories/Activity/ActivityRepository.php, app/Repositories/Project/ProjectRepository.php
Included Storage class for where its instances were being used.
=> Included Storage Facade for some repository files.

app/Http/Controllers/Api/V1/PlaylistController.php, app/Http/Resources/V1/H5pActivityResource.php, app/Repositories/Playlist/PlaylistRepository.php, app/Repositories/Playlist/PlaylistRepositoryInterface.php, routes/api.php
=> Load playlist lti preview

app/Http/Controllers/Api/V1/ProjectController.php, app/Repositories/Project/ProjectRepository.php, app/Repositories/Project/ProjectRepositoryInterface.php, config/constants.php, routes/api.php
fetch recently created projects and by default user
=> fetch recently created projects and by default user

app/Http/Controllers/Api/V1/PlaylistController.php
Playlist lti fix - playlist lti with activities
=> playlist lti with activities

app/Services/GoogleClassroom.php
Fixed activity shared URL for publishing since environment variable could now be relative.
=> Fixed activity shared URL for publishing 

app/Http/Controllers/Api/V1/ProjectController.php
Project load with public and shared status
=> Project load with public and shared status

app/Http/Controllers/Api/V1/ActivityController.php
=> Activity H5P Update

app/Repositories/Playlist/PlaylistRepository.php
set activity title from activities table/model not from h5p-contents table/model
=> activity title from activities model not from h5p-content

app/Repositories/Playlist/PlaylistRepository.php
Ativity thumb_url fix on /load-shared
=> Ativity thumb_url fix

app/Http/Controllers/Api/V1/ActivityController.php, routes/api.php
Activity Shared H5P data added
=> Activity Shared H5P data added

app/Repositories/Project/ProjectRepository.php
Project Sample - set activity model title and code cleaning
=> Project Sample - set activity model title

app/Http/Resources/V1/ActivityItemResource.php
activity items include demo fields
=> activity items include demo fields

app/Http/Resources/V1/ActivityResource.php, app/Http/Resources/V1/PlaylistResource.php, app/Http/Resources/V1/ProjectResource.php
Fixing memory issues with project listings
=> Projects query fix

app/Http/Controllers/Api/V1/H5pController.php, routes/api.php
=> H5P Embed endpoint

H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php
=> h5p export set url

app/Http/Controllers/Api/V1/ProjectController.php, app/Http/Resources/V1/ProjectDetailResource.php, app/Http/Resources/V1/ProjectDetailedResource.php, app/Http/Resources/V1/ProjectPlaylistOnlyResource.php, routes/api.php
list projects with playlists and activities
=> list projects with detail

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Controllers/Api/V1/ProjectController.php, app/Http/Controllers/Auth/AuthController.php
CUR-499 - Updating API response message on successful registration
CUR-504 - Increasing Thumbnail upload size to 1 MB
(Hold merge until tomorrow)
=> Registration success msg updated + increased thumbnail size to 1MB

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Controllers/Api/V1/ProjectController.php
File upload limit has to be increased to 100 MB.
=> CUR-504 - Increasing file upload limit to 100MB

database/migrations/2020_09_17_101851_drop_unique_name_from_users_table.php
remove unique name constraint from users table
=> remove unique name constraint from users table

database/migrations/2020_09_17_000000_change_default_membership_type_id_in_users_table.php
This migration changes the default user membership type to free.
=> Demo membership has been deprecated. 

app/Http/Controllers/Api/V1/Admin/ProjectController.php, app/Http/Requests/Admin/StoreLmsSetting.php, app/Http/Resources/V1/Admin/LmsSettingResource.php, app/Repositories/Admin/Project/ProjectRepository.php, routes/api.php
- Indexes update script tweaks 
- Addition for toggling the public status of any project from admin panel
=> Public indexes toggle implementation

app/Http/Resources/V1/PlaylistActivityShortResource.php, app/Http/Resources/V1/ProjectPlaylistShortResource.php, app/Http/Resources/V1/ProjectPublicResource.php
projects short result set for lti deeplink
=> projects short result set for lti deeplink

H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php
add content metadata to preview response
=> add content metadata to preview response

app/Http/Controllers/Api/V1/ProjectController.php
=> CUR-597-Cloning in background

H5P/laravel-h5p/src/LaravelH5p/Repositories/LaravelH5pRepository.php
H5P Editor - Support uppercase for file extension while uploading
=> H5P Editor - Support uppercase for file extension while uploading

app/Http/Resources/V1/SearchResource.php, app/Models/Playlist.php
Added the project image as the default image for the playlist in search.
=> Added the project image as the default image for the playlist in search.

routes/api.php
=> reordering of projects

app/Http/Controllers/Api/V1/Admin/ActivityItemController.php, app/Http/Controllers/Api/V1/Admin/ActivityTypeController.php, app/Http/Controllers/Api/V1/Admin/LmsSettingController.php, app/Http/Controllers/Api/V1/Admin/ProjectController.php, app/Http/Controllers/Api/V1/Admin/UserController.php, app/Http/Resources/V1/Admin/ProjectResource.php, app/Models/Project.php, app/Repositories/Admin/Project/ProjectRepository.php, app/Repositories/Project/ProjectRepository.php, database/migrations/2020_10_09_101720_add_is_user_starter_field_to_projects_table.php, routes/api.php
- Created migration for adding user_starter flag.
- Update this flag for existing records
- Set this flag to true if cloned from project is starter
**Note**: Migration command needs to be run
=> CUR-612 Identify is user project is a starter project

app/Http/Resources/V1/Admin/ProjectResource.php, app/Repositories/Admin/Project/ProjectRepository.php
- Format the created at and updated at field for projects listing
- Exclude the user starter projects conditionally
=> Implemented condition for excludig the user starter projects

app/User.php
Sort user projects by asc order as directed by Qammar.
=> Sort user projects by asc order as directed by Qammar.

app/CurrikiGo/Canvas/Client.php, app/CurrikiGo/Canvas/Commands/CreateCourseEnrollmentCommand.php, app/CurrikiGo/Canvas/Commands/GetCourseEnrollmentCommand.php, app/CurrikiGo/Canvas/Commands/GetCoursesCommand.php, app/CurrikiGo/Canvas/Commands/GetUsersCommand.php, app/CurrikiGo/Canvas/Helpers/Enrollment.php, app/CurrikiGo/Canvas/Playlist.php, app/Models/CurrikiGo/LmsSetting.php, database/migrations/2020_10_08_080140_add_lms_login_id_to_lms_settings.php
Canvas Publish - enroll user as teacher while creating course
=> Canvas Publish - enroll user as teacher while creating course

app/Http/Requests/Admin/StoreLmsSetting.php, app/Http/Resources/V1/Admin/LmsSettingResource.php, app/Models/CurrikiGo/LmsSetting.php
- Added new field in LMS Settings CRUD
=> Added new field in LMS Settings CRUD

app/Http/Requests/Admin/StoreUser.php, app/Http/Requests/Auth/RegisterRequest.php, app/Models/Project.php, app/Repositories/Admin/User/UserRepository.php, app/Repositories/Project/ProjectRepository.php, app/Repositories/User/UserRepository.php, app/User.php
- Project model type-cast for boolean fields
=> Type casting for boolean fields of project model

app/CurrikiGo/Canvas/Playlist.php
canvas publish - fixed user retrieval on 0 index
=> canvas publish - fixed user retrieval on 0 index

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Controllers/Api/V1/PlaylistController.php, app/Http/Controllers/Api/V1/ProjectController.php
remove is public check from cloning
=> remove is public check

app/Http/Controllers/Api/V1/SearchController.php
=> feature/CUR-82-update-api-docs Updated docs for search API.

app/Http/Controllers/Api/V1/Admin/ProjectController.php, app/Http/Controllers/Api/V1/ProjectController.php, app/Models/Project.php, app/Repositories/Admin/Project/ProjectRepository.php, app/Repositories/Project/ProjectRepository.php, routes/api.php
- Removed the old unused functions as is_public and elasticsearch columns will be removed
- Updated the functions according to new indexing field
=> admin-showcase-for-indexing-requested-projects

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Requests/V1/ActivityRequest.php
- Subject and education field id should be null-able as per database and our api doc
- Fix the null value issue if receive null value from front-end
=> Fix the validation issue for education and subject field

app/Http/Controllers/Api/V1/Admin/UserController.php, app/Http/Resources/V1/Admin/UserResource.php, app/Repositories/Admin/User/UserRepository.php, app/User.php, routes/api.php
- Assign and remove user role from admin panel
=> Assign and remove user role

app/Jobs/ClonePlayList.php, app/Jobs/CloneProject.php
- Clone Projects, playlists background jobs exception handling
=> Clone Projects, playlists background jobs exception handling

app/Console/Kernel.php, app/Http/Controllers/Auth/AuthController.php, app/Http/Requests/Admin/StoreUser.php, app/Http/Requests/Admin/UpdateUser.php, app/Http/Requests/Auth/RegisterRequest.php, app/Http/Resources/V1/Admin/UserResource.php, app/Imports/UsersImport.php, app/Repositories/Admin/User/UserRepository.php, public/sample/users-import-sample.csv
- Organization fields required validations for bulk import
=> Organization fields required validations for bulk import

app/Http/Controllers/Api/V1/Admin/QueueMonitorController.php, app/Http/Resources/V1/Admin/QueueMonitorJobResource.php, app/Http/Resources/V1/Admin/QueueMonitorResource.php, app/Jobs/CalculateActivityStorage.php, app/Models/QueueMonitor.php, app/Providers/QueueMonitorProvider.php, app/Repositories/Admin/BaseRepository.php, app/Repositories/Admin/QueueMonitor/QueueMonitorRepository.php, app/Services/QueueMonitor.php, app/helpers.php, config/app.php, database/migrations/2020_10_22_124159_create_queue_monitor_table.php, routes/api.php
- Queue Logs
- Queue Monitor
- Retry specific or all Failed Jobs
- Delete specific or all failed Jobs
=> CUR-640 interface for queue jobs logs

app/Http/Controllers/Api/V1/UserController.php, app/Http/Resources/V1/NotificationListResource.php, app/Http/Resources/V1/NotificationResource.php, routes/api.php, storage/responses/notifications/notifications.json
CUR-654-list and read notifications apis
=> CUR-654-list and read notifications apis

app/CurrikiGo/Canvas/Commands/CreateCourseCommand.php, app/CurrikiGo/Canvas/Commands/GetCoursesCommand.php, app/CurrikiGo/Canvas/Course.php, app/CurrikiGo/Canvas/Helpers/Course.php, app/CurrikiGo/Canvas/Playlist.php
Publish to Canvas based on userId and projectId
=> Publish to Canvas based on userId and projectId

app/Repositories/Activity/ActivityRepository.php
- Hotfix for clone activity issue related to permissions.
=> [HotFix] Change owner of new content directory to default (www-data)

app/Http/Resources/V1/Admin/UserResource.php, app/Models/Traits/GlobalScope.php, app/Repositories/Admin/User/UserRepository.php, app/helpers.php
- Sort and filter by user registration dates
=> [CUR-667] User created at date filter and sorting

app/Http/Controllers/Api/V1/UserController.php, app/Http/Resources/V1/NotificationListResource.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, routes/api.php
Feature/enhancement in notification messages
=> [CUR-689] - Enhancement in notifications

app/Http/Controllers/Api/V1/GoogleClassroomController.php, app/Http/Requests/V1/GCGetStudentSubmissionRequest.php, app/Http/Requests/V1/GCSummaryPageAccessRequest.php, app/Http/Resources/V1/GCStudentResource.php, app/Http/Resources/V1/GCSubmissionResource.php, app/Services/GoogleClassroom.php, app/Services/GoogleClassroomInterface.php, routes/api.php, storage/responses/google-classroom/google-classroom-student.json, storage/responses/google-classroom/google-classroom-submission.json
and fetching student's submission added.
=> [CUR-658] API end points for verifying access to student's submission

app/Repositories/Admin/ActivityType/ActivityTypeRepository.php
New items columns is added on admin side for activities types listing page
- Enable relation searching for new column
=> [CUR-655] Enable relation searching for activity types listing

app/Notifications/CloneNotification.php
[CUR-695] - Change time format
=> [CUR-695] - Change time format

app/Http/Controllers/Api/V1/GoogleClassroomController.php, app/Http/Controllers/Api/V1/XapiController.php, app/Http/Resources/V1/GCStudentResource.php, app/Services/GoogleClassroom.php, app/Services/GoogleClassroomInterface.php
Also, updated scopes for Google classroom, and the student resource.
=> [CUR-713] Improved access logic for the results summary page.

app/Services/GoogleClassroom.php
This is an interim fix as we don't want the recent assignment flow to work on production yet.
=> [CUR-717] - Reverted GC assignment link to 'shared' activity link

app/Console/Kernel.php, app/Http/Controllers/Auth/AuthController.php, app/Http/Requests/Admin/StoreUser.php, app/Http/Requests/Admin/UpdateUser.php, app/Http/Requests/Auth/RegisterRequest.php, app/Http/Resources/V1/Admin/UserResource.php, app/Imports/UsersImport.php, app/Repositories/Admin/User/UserRepository.php, public/sample/users-import-sample.csv
- Organization fields validations
=> [Hotfix] Organization fields validations

app/Http/Controllers/Api/V1/PlaylistController.php, app/Repositories/Playlist/PlaylistRepository.php, routes/api.php
=> fix null order issue

app/Services/LearnerRecordStoreService.php
This is for recreating the student's results summary page.
=> [CUR-763] Made category property optional when filtering for skipped statements.

.env.example, config/database.php
Support Read/Write Database Connections
=> RCL-17 Support Read/Write Database Connections

app/CurrikiGo/Canvas/Course.php, app/CurrikiGo/Canvas/Helpers/Course.php, app/CurrikiGo/Canvas/Playlist.php
Added date timestamp to sis id string.
Also, improved string to human-friendly URL conversion.
=> [CUR-770] - Fixed duplicate sis id issue for Canvas courses

app/Http/Requests/V1/SearchRequest.php, app/Http/Resources/V1/SearchResource.php, storage/responses/search/advance.json, storage/responses/search/dashboard.json
Added checks on to date to be same or after the from date.
Added the date in search response.
=> Added checks on to date to be same or after the from date.

config/laravel-h5p.php
hotfix to support questionnaire h5p. this branch is off from master branch
=> hotfix - support questionnaire h5p

app/Services/LearnerRecordStoreService.php, app/Services/LearnerRecordStoreServiceInterface.php
=> [CUR-870] Removed aggregate line-items from the summary page

H5P/laravel-h5p/src/LaravelH5p/Helpers/H5pHelper.php, H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php, H5P/laravel-h5p/src/LaravelH5p/Repositories/LaravelH5pRepository.php
IB content backward compatibility for sequential logic
=> IB content backward compatibility for sequential logic

H5P/laravel-h5p/src/LaravelH5p/Helpers/H5pHelper.php, H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php, H5P/laravel-h5p/src/LaravelH5p/Repositories/LaravelH5pRepository.php, app/CurrikiGo/LRS/InteractionFactory.php, app/CurrikiGo/LRS/InteractionSummary.php, app/CurrikiGo/LRS/Interactions/ChoiceSummary.php, app/CurrikiGo/LRS/Interactions/FillInSummary.php, app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php, app/Http/Controllers/Api/V1/CurrikiGo/OutcomeController.php, app/Http/Controllers/Api/V1/PlaylistController.php, app/Http/Requests/V1/SearchRequest.php, app/Http/Resources/V1/SearchResource.php, app/Models/Project.php, app/Repositories/Activity/ActivityRepository.php, app/Repositories/Playlist/PlaylistRepository.php, app/Services/LearnerRecordStoreConstantsInterface.php, app/Services/LearnerRecordStoreService.php, app/Services/LearnerRecordStoreServiceInterface.php, config/laravel-h5p.php, routes/api.php, storage/responses/outcome/student-result-summary.json, storage/responses/search/advance.json, storage/responses/search/dashboard.json
Use normal "merge" option to merge into staging.
=> Development to staging

app/Http/Controllers/Api/V1/CurrikiGo/OutcomeController.php, app/Services/LearnerRecordStoreConstantsInterface.php, app/Services/LearnerRecordStoreService.php, app/Services/LearnerRecordStoreServiceInterface.php
Also, updated logic to get attempt IRI using a regex.
=> [CUR-937] - Updated summary page to use 'submitted-curriki' verb.

H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php, app/Http/Controllers/Api/V1/H5pController.php, app/Models/CurrikiGo/ContentUserDataGo.php, app/Providers/RepositoryServiceProvider.php, app/Repositories/CurrikiGo/ContentUserDataGo/ContentUserDataGoRepository.php, app/Repositories/CurrikiGo/ContentUserDataGo/ContentUserDataGoRepositoryInterface.php, database/migrations/2021_02_09_142702_create_h5p_contents_user_data_go_table.php, routes/api.php
H5P data persistence for H5P. I manage the user state. 
need to run migration:
database/migrations/2021_02_09_142702_create_h5p_contents_user_data_go_table.php
=> H5P data presistence for H5P

H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php
assign arbitrary user details to H5P integration meta for GCR user
=> assign arbitrary user details to H5P integration meta for GCR user

H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php, app/Http/Controllers/Api/V1/H5pController.php, config/laravel-h5p.php
added saveFeq and manage response
=> Bugfix/viv 52 data persistence - added saveFeq and manage response

app/Http/Controllers/Api/V1/GoogleClassroomController.php, app/Http/Requests/V1/GCCopyProjectRequest.php, app/Providers/AuthServiceProvider.php, app/Services/GoogleClassroom.php
Also, fixed a bug and allowed listing of GCRs courses where  user is the teacher only.
=> [CUR-961] - Allowing publishing of shared projects to Google Classroom.

app/Http/Controllers/Api/V1/CurrikiGo/OutcomeController.php, app/Services/LearnerRecordStoreService.php, app/Services/LearnerRecordStoreServiceInterface.php
Also, updated logic to remove aggregate h5p's skipped statements for any quizzes that were attempted later, but skipped initially.
=> [CUR-983] - Accumulating student responses across all attempts.

H5P/laravel-h5p/src/LaravelH5p/Helpers/H5pHelper.php
interactivebook metadata repair which fetching from database.
=> interactivebook metadata repair

H5P/laravel-h5p/src/LaravelH5p/Helpers/H5pHelper.php
skip h5p libraries updates from upload feature
=> [CUR-933] skip h5p libraries updates from upload feature

database/migrations/2021_03_18_080505_remove_unique_key_statement_uuid.php
=> [CUR-1024] - Removed unique key constraint on statement_uuid column

app/CurrikiGo/LRS/InteractionSummary.php, app/Http/Controllers/Api/V1/TeamController.php, app/Http/Controllers/Api/V1/UserController.php
add two methods to strip the html tags from the title and description of the summery.
=> [CUR-1051] Strip html tags from summary page.

app/Repositories/Project/ProjectRepository.php
Add Activity Sort Order For Share Page as it is on Preview Page.
=> [CUR-1115] Add Activity Sort Order For Share Page as it is on Preview Page.

app/Repositories/H5pContent/H5pContentRepository.php
fetch brightcove video if related activity exist
=> fetch brightcove video if related activity exist

app/Http/Controllers/Api/V1/BrightcoveController.php, app/Repositories/H5pContent/H5pContentRepository.php, app/Repositories/H5pContent/H5pContentRepositoryInterface.php, routes/integrations.php
brightcove - added params to query the video
=> brightcove - added params to query the video

database/seeds/OrganizationRoleTypeSeeder.php, database/seeds/OrganizationSeeder.php
Fixed org multi tenancy seeder.
=> Fixed org multi tenancy seeder.

database/seeds/OrganizationRoleTypeSeeder.php
Updated seeder to set deafult role for existing user to "course_creator" instead of "member".
=> Updated seeder to set default role for existing user to "course_creator" instead of "member".

app/Http/Controllers/Auth/AuthController.php, app/Http/Requests/Auth/SsoLoginRequest.php, app/Http/Requests/Auth/SsologinLoginRequest.php, app/Models/SsoLogin.php, app/User.php, database/migrations/2021_04_22_111101_create_sso_logins_table.php, routes/api.php
Need to run migration "2021_04_22_111101_create_sso_logins_table.php" for this feature to work.
=> [CUR-1186] Create an end point on Curriki Studio to consume user info for SSO login

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Requests/V1/ActivityCreateRequest.php, app/Http/Requests/V1/ActivityEditRequest.php
Refactored edit activity action, added edit activity validation.
=> [CUR-1200] - Refactored edit activity action, added edit activity validation.

app/Http/Controllers/Api/V1/ActivityController.php
removed "data" parameter from request for activity update.
=> [CUR-1179] Edit Activity Issue fix 

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Models/OrganizationRoleType.php, app/Repositories/Organization/OrganizationRepository.php, app/Repositories/Organization/OrganizationRepositoryInterface.php, database/seeds/OrganizationPermissionTypeSeeder.php, routes/api.php
Refactored the createSuborganization() function to duplicate authentiatedUsers role and permissions in sub org.
Refactored the addRole() function to return OrganizationUserRole object.
Added users relationship function to OrganizationUserRole Model.
Added "organization:add-role" to OrganizationPermissionTypeSeeder.
Removed duplicate "->name(h5p.ajax.content-user-data);" from one of the routes in "api.php"
=> [CUR-1152] Resolved issue with role not visible on navigation to suborg

app/Policies/OrganizationPolicy.php, database/seeds/OrganizationPermissionTypeSeeder.php
Replaced "organization:update" with "organization:edit" in OrganizationPolicy.
=> [CUR-1204] Resolved issue with org editing being unauthorized

app/Models/QueryBuilders/SearchFormQueryBuilder.php
- Limit the search to title and description only not other columns like H5P etc.
- Removed the duplicated code for filtering by h5pLibraries.
=> [CUR-1083] Search title and description only

app/Notifications/CloneNotification.php
=> email-turned-off

app/Models/QueryBuilders/SearchFormQueryBuilder.php
Make Elasticsearch inclusive till last second of to-date.
=> [VIV-116] Make Elasticsearch inclusive till last second of to-date.

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Requests/V1/SuborganizationInviteMember.php
please review the code and pull it at dev server, thanks!
=> bugfix for CUR-1247-invite-existed-users

app/helpers.php
=> fixed issue in cloning

app/Http/Resources/V1/SearchResource.php
Added project_id in search resource response.
=> [CUR-1162] Added project_id in search resource response.

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Controllers/Auth/AuthController.php, app/Http/Requests/V1/SuborganizationSave.php, app/Http/Requests/V1/SuborganizationUpdate.php, app/Models/Organization.php, app/Repositories/Organization/OrganizationRepository.php, app/Repositories/Organization/OrganizationRepositoryInterface.php, database/migrations/2021_05_06_204114_add_self_registration_to_organizations_table.php
- Updated create and update org APIs to save self_registration and updated docs, validations.
- Added the check on register for self_registration and updated logic.
=> [CUR-1199] Manage org self_registration.

app/Http/Controllers/Auth/AuthController.php
Added self registration on google login.
Updated status code for error to "400".
=> [CUR-1199] Added self registration on google login.

app/Repositories/Group/GroupRepository.php, app/Repositories/Team/TeamRepository.php
=> CUR-1293-issue-fixing

app/helpers.php
Hotfix-unable to clone project- issue fixed
=> Hotfix-unable to clone project- issue fixed

app/Repositories/Group/GroupRepository.php, app/Repositories/Team/TeamRepository.php
please review this PR for CUR-1429
=> CUR-1429 fixing

app/Repositories/Organization/OrganizationRepository.php
Resolved issue with assigning user role permissions on create sub organization.
=> [CUR-1284] Resolved issue with assigning user role permissions on create sub organization

H5P/laravel-h5p/src/LaravelH5p/Repositories/LaravelH5pRepository.php
support html htm file types for h5p upload
=> support html htm file types for h5p upload

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Repositories/Organization/OrganizationRepositoryInterface.php
Add check on delete and remove org user API to prevent user inherited from a parent org getting deleted/removed.
=> [CUR-1518] - Add check on delete and remove org user API to prevent user inherited from a parent org getting deleted/removed.

app/Http/Controllers/Api/V1/ProjectController.php
Implemented clone project functionality by Admin
=> Implmented clone project by admin

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Repositories/QueueMonitor/QueueMonitorRepository.php
Please review this PR for feedback fixing.
=> CUR-1535 and CUR-1538 fixing

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Requests/Admin/OrganizationUpdate.php, app/Http/Requests/V1/SuborganizationUpdate.php
Updated checks for different org parent-id while updating org.
=> [CUR-1539] Updated checks for different org parent-id while updating org.

app/Http/Controllers/Auth/AuthController.php, app/Http/Requests/Admin/OrganizationCreate.php, app/Http/Requests/Admin/OrganizationUpdate.php, app/Http/Requests/V1/SuborganizationSave.php, app/Http/Requests/V1/SuborganizationUpdate.php, app/Providers/AppServiceProvider.php, app/Rules/Lowercase.php
Created custom error response format to use throughout the application.
Updated error response when self registration is disabled for register and login with google.
Created custom rule to check for lowercase throughout the application.
Added check for lowercase on domain in admin and studio create and updated APIs.
=> [CUR-1552] Updated error response format if self registration is disabled.

app/Http/Controllers/Api/V1/SuborganizationController.php
Resolved issue with delete & remove org user.
=> [CUR-1539] Resolved issue with delete & remove org user.

app/Repositories/Organization/OrganizationRepositoryInterface.php, database/seeds/OrganizationUserRoleSeeder.php
Added seeder to create new roles per org for default roles.
Added missing update function to Interface.
=> [CUR-1581] Added seeder to create new roles per org for default roles.

database/seeds/OrganizationPermissionTypeSeeder.php
Added edit-role and view-role permissions.
=> [CUR-1605] Added edit-role and view-role permissions.

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Requests/V1/StoreLmsSetting.php, app/Http/Requests/V1/UpdateLmsSetting.php, app/Policies/OrganizationPolicy.php, database/seeds/OrganizationPermissionTypeSeeder.php
CUR-1605 and some validation fixing
=> CUR-1605 and some validaiton fixing

app/Http/Requests/V1/SuborganizationGetUsersRequest.php
Added check on user search query to be minimum two strings in length.
=> [CUR-1604] Added check on user search query to be minimum two strings in length.

app/Http/Requests/V1/SuborganizationDeleteUserRequest.php
Added check to prevent user from removing or deleting itself.
=> [CUR-1590] Added check to prevent user from removing or deleting itself.

app/Repositories/Organization/OrganizationRepository.php
Updated member options API end point to list all users including admins.
=> Updated member options API end point to list all users including admins.

database/migrations/2021_07_02_161511_create_composite_unique_index_on_organization_role_permissions_table.php, database/seeds/OrganizationRolePermissionSeeder.php
Updated seeder to assign new permissions to default roles.
Added migration to create composite unique index on organization role permissions table.
=> Updated seeder to assign new permissions to default roles.

app/Repositories/Playlist/PlaylistRepository.php, app/Repositories/Project/ProjectRepository.php
=> fixed issue in import project

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Controllers/Api/V1/PlaylistController.php, app/Http/Controllers/Api/V1/ProjectController.php, app/Policies/ActivityPolicy.php, app/Policies/PlaylistPolicy.php, app/Policies/ProjectPolicy.php, app/Repositories/Project/ProjectRepositoryInterface.php
Updated the clone policy for activity, playlist and project to allow user to clone them from other org that appear in search.
=> [CUR-1614] Allowed items from other org in search to clone

app/Http/Requests/V1/SuborganizationInviteMember.php
Updated checks to allow users to resend external user invitations.
=> [CUR-1710] Updated checks to allow users to resend external user invitations.

app/Http/Requests/V1/SuborganizationInviteMember.php
Updated checks to allow users to resend external user invitations.
=> Updated checks to allow users to resend external user invitations.

app/Http/Resources/V1/SearchResource.php, app/Http/Resources/V1/SearchUserResource.php, app/Repositories/Activity/ActivityRepository.php
Refactored search response, added author data.
Added search by author "first_name", "last_name" and "email".
=> [CUR-1718] Refactored search response, added author data.

app/Http/Resources/V1/SearchResource.php
Reverted the refactored search response, removed author data.
=> Reverted the refactored search response, removed author data.

app/Http/Resources/V1/SearchResource.php
Resolved issue with listing project id in search.
=> Resolved issue with listing project id in search.

app/Http/Resources/V1/SearchResource.php
Added user details in elastic search response.
=> Added user in elastic search response.

app/Http/Resources/V1/SearchResource.php
Resolved issue with listing user in search response.
=> Resolved issue with listing user in search response.

app/Http/Controllers/Api/V1/GoogleClassroomController.php, app/Http/Resources/V1/H5pOrganizationResource.php
=> Added learn safe fields in h5p settings

app/Repositories/Activity/ActivityRepository.php
Resolved issue with search for content by author list other authors as well.
=> [CUR-1718] Resolved issue with search for content by author list other authors

app/Repositories/Organization/OrganizationRepository.php
Resolved issue with author name display.
=> [CUR-1783] Resolved issue with author name display.

app/Repositories/Organization/OrganizationRepository.php
Resolved issue with searching email with underscore.
=> [CUR-1806] Resolved issue with searching email with underscore.

database/seeds/ActivitySubjectIdSeeder.php
Added seeder to replace old subject values with new ones.
=> [CUR-988] Added seeder to replace old subject values with new ones.

app/Http/Controllers/Api/V1/GoogleClassroomController.php, app/Models/GoogleClassroom.php, app/Providers/RepositoryServiceProvider.php, app/Repositories/GoogleClassroom/GoogleClassroomRepository.php, app/Repositories/GoogleClassroom/GoogleClassroomRepositoryInterface.php, app/Services/GoogleClassroom.php, database/migrations/2021_08_06_064829_create_gc_class_api_data.php
Please run migration e.g.
"php artisan migrate --path=/database/migrations/2021_08_06_064829_create_gc_class_api_data.php"
=> [VIV-188] Store the classID/invite link in the table while a teacher publishes

app/Http/Requests/V1/SuborganizationUpdate.php
Removed check for parent id from edit org API.
=> Removed check for parent id from edit org API.

app/Repositories/Organization/OrganizationRepository.php
Copy parent org roles while creating new sub org.
=> [CUR-1868] Copy parent org roles while creating new sub org.

app/Http/Controllers/Api/V1/ActivityController.php, app/Policies/ActivityPolicy.php, app/Policies/PlaylistPolicy.php, app/Policies/ProjectPolicy.php, app/Providers/AuthServiceProvider.php, app/Repositories/Activity/ActivityRepository.php
Added int parsing for constants comparisons develop branch.
=> [CUR-1895] Added int parsing for constants comparisons develop branch.

app/Http/Controllers/Api/V1/ActivityController.php, app/Policies/ActivityPolicy.php, app/Policies/PlaylistPolicy.php, app/Policies/ProjectPolicy.php, app/Providers/AuthServiceProvider.php, app/Repositories/Activity/ActivityRepository.php
Added int parsing for constants comparisons.
=> [CUR-1895] Added int parsing for constants comparisons.

app/Models/GoogleClassroom.php, app/Repositories/GoogleClassroom/GoogleClassroomRepository.php, app/Services/GoogleClassroom.php, database/migrations/2021_08_20_152911_add_teacher_email_in_gclass_api_data.php
Please run migration "php artisan migrate --path=/database/migrations/2021_08_20_152911_add_teacher_email_in_gclass_api_data.php"
=> Add Teacher's email of google & curriki account in google api data 

app/Models/GoogleClassroom.php, app/Repositories/GoogleClassroom/GoogleClassroomRepository.php, app/Services/GoogleClassroom.php, database/migrations/2021_08_25_153130_remove_gmail_from_gclass_api_data.php
Please run this migration "php artisan migrate --path=/database/migrations/2021_08_25_153130_remove_gmail_from_gclass_api_data.php"
=> Remove Gmail field from Gclass Api Data

app/Http/Controllers/Api/V1/GoogleClassroomController.php, app/Http/Requests/V1/SuborganizationSave.php, app/Http/Requests/V1/SuborganizationUpdate.php, app/Http/Resources/V1/H5pOrganizationResource.php
learn safe changes for staging and vivensity branch
=> learn safe changes for staging and vivensity branch

database/seeds/OrganizationRolePermissionSeeder.php
Updated organization role permission seeder to exclude group permissions.
=> Updated organization role permission seeder to exclude group permissions.

app/Http/Resources/V1/ActivityResource.php
Added extra parameter to activity resource service to skip h5p content when requesting the playlist activities
=> CUR-1969 request optimization

app/Models/GoogleClassroom.php, app/Repositories/GoogleClassroom/GoogleClassroomRepository.php, app/Services/GoogleClassroom.php, database/migrations/2021_08_25_153130_remove_gmail_from_gclass_api_data.php, jenkins/Jenkinsfile.stage
Merge staging to develop and resolve conflicts
=> Merge staging to develop & resolve conflicts

app/Repositories/Activity/ActivityRepository.php
=> missing content images issue

.env.example
Turn off emails from instances.
=> Turn off emails from instances

.env.example
Hotfix/move broadcast type into env
=> Hotfix/Update Env example file for turn off email

app/Notifications/ProjectExportNotification.php
Append the exported file link on project export notification
=> Append the exported file link on project export notification

app/Http/Resources/V1/ProjectResource.php
CUR-2053 project detail issue fixing
=> CUR-2053 project detail issue fixing

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Resources/V1/ProjectResource.php
=> CUR-2082 activity issue

.gitignore
Added composer lock and composer phar to gitignore.
https://github.com/ActiveLearningStudio/ActiveLearningStudio-API/commit/80062186dab18fd810ff5d637fe0039b5faca232
=> Added composer lock and composer phar to gitignore.

H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php, app/Http/Controllers/Api/V1/H5pController.php, app/Models/CurrikiGo/ContentUserDataGo.php, app/Repositories/CurrikiGo/ContentUserDataGo/ContentUserDataGoRepository.php, app/Repositories/CurrikiGo/ContentUserDataGo/ContentUserDataGoRepositoryInterface.php, database/migrations/2021_09_10_130714_add_submissionid_into_h5p_contents_user_data_go_table.php, database/migrations/2021_09_17_115108_alter_table_h5p_contents_user_data_go_add_submissionid_pk.php, database/seeds/H5PContentsUserDataGo.php
Cherry picked [CUR-2012] feature for GCR data persistence update.
=> Deployment to Staging from Develop (Cherry picked)

app/Repositories/Activity/ActivityRepository.php
Resolved issue with Elsaticsearch showing records for users having no projects.
=> Resolved issue with Elsaticsearch showing records for users having no projects.

app/Http/Controllers/Api/V1/ProjectController.php
=> Project Unshare Issue Fix

app/Http/Controllers/Api/V1/GoogleClassroomController.php, app/Services/GoogleClassroom.php
=> [VIV-226] Fixed the UserId issue and also remove extra values added

app/Http/Controllers/Api/V1/CurrikiGo/ExtractXAPIJSONController.php
=> [CUR-2262] - Making Alternate link unique by appending class id.

app/Http/Controllers/Api/V1/GoogleClassroomController.php, app/Http/Requests/V1/GCPublishActivityRequest.php, app/Services/GoogleClassroom.php, app/Services/GoogleClassroomInterface.php, storage/responses/google-classroom/google-classroom-publish-activity.json
And includes some fixes for publishing 'activity' as well.
=> [CUR-1630] Publishing playlist to Google Classroom

app/Http/Controllers/Api/V1/CurrikiGo/ExtractXAPIJSONController.php
It will be left as blank in the database for such links.
=> [CUR-2420] - Hotfix - Fixed Alternate URL for Shared activity links.

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Controllers/Api/V1/PlaylistController.php, app/Http/Controllers/Api/V1/ProjectController.php
=> Message changed

app/Http/Controllers/Auth/AuthController.php
Added check for existing user on google signup
=> CUR-2445: Added check for existing user on google signup

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Controllers/Api/V1/PlaylistController.php, app/Http/Controllers/Api/V1/ProjectController.php
Add line break on notification messages
=> Add line break on notification messages

.env.example, .gitignore, app/Http/Controllers/Api/V1/WhiteboardController.php, app/Http/Requests/V1/WhiteboardRequest.php, app/Services/WhiteboardInterface.php, app/Services/WhiteboardService.php, config/whiteboard.php, routes/api.php
=> whiteboard integration initial code

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Controllers/Api/V1/PlaylistController.php, app/Http/Controllers/Api/V1/ProjectController.php
Changes export/duplicate message.
=> Changes export/duplicate message

app/Notifications/ProjectExportNotification.php, app/Notifications/ProjectImportNotification.php
Add space on notification messages
=> Add space on notification messages

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Requests/V1/SuborganizationSave.php, app/Http/Requests/V1/SuborganizationUpdate.php, app/Http/Resources/V1/OrganizationResource.php, app/Models/Organization.php, database/migrations/2021_11_15_081553_add_noovo_client_id_to_organizations_table.php, storage/responses/organization/suborganization.json
Add noovo client id in organiziation
=> Add noovo client id in organiziation

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Requests/V1/SuborganizationSave.php, app/Http/Requests/V1/SuborganizationUpdate.php, app/Http/Resources/V1/ActivityResource.php, app/Http/Resources/V1/OrganizationResource.php, app/Http/Resources/V1/PlaylistResource.php, app/Http/Resources/V1/ProjectResource.php, app/Http/Resources/V1/UserProjectResource.php, database/migrations/2021_11_18_112230_add_google_class_flags_to_organizations_table.php, storage/responses/activity/activities.json, storage/responses/activity/activity.json, storage/responses/organization/suborganizations.json, storage/responses/playlist/playlist.json, storage/responses/playlist/playlists.json, storage/responses/project/project.json, storage/responses/project/projects.json
Has one migration:
database/migrations/2021_11_18_112230_add_google_class_flags_to_organizations_table.php
=> [CUR-2409] Adding GCR publishing admin config

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Requests/V1/SuborganizationSearchRequest.php, app/Repositories/Organization/OrganizationRepository.php
=> updated code for this ticket

app/Console/Commands/importProjects.php, app/Repositories/Project/ProjectRepository.php, config/import-mapped-device.php
Import script on mapped devices
=> Import script on mapped devices

app/Http/Controllers/Api/V1/ActivityController.php, app/Http/Controllers/Api/V1/PlaylistController.php, app/Http/Controllers/Api/V1/ProjectController.php, app/Http/Resources/V1/ActivitySearchPreviewResource.php, app/Http/Resources/V1/PlaylistSearchPreviewResource.php, app/Http/Resources/V1/ProjectSearchPreviewResource.php, app/Policies/ProjectPolicy.php, app/Repositories/Project/ProjectRepositoryInterface.php, routes/api.php, storage/responses/project/project-search-preview.json
Defined authorization policy for search preview of project, playlists and activities.
Created response resources for search preview of project, playlists and activities.
Compiled the routes and action to fetch projects, playlists and activities for search preview.
=> CUR-2582: Created search results preview pages

app/Repositories/Activity/ActivityRepository.php, app/Repositories/Project/ProjectRepository.php
hotfix import forward slash issue
=> hotfix import forward slash issue

app/Console/Commands/importProjects.php, app/Repositories/Project/ProjectRepository.php, config/import-mapped-device.php
import through command feature hotfix
=> import through command feature hotfix

app/Jobs/ExportProjecttoNoovo.php, database/migrations/2021_11_30_120027_add_noovo_group_to_teams_table.php
=> rename noovo columns

app/Http/Controllers/Api/V1/UserController.php, app/Http/Requests/V1/CheckUserEmailRequest.php, routes/api.php
Added API to search for existing user when adding user from Admin panel.
=> CUR-2654: Check user email before adding to org

app/Jobs/ExportProjecttoNoovo.php, app/Models/NoovoLogs.php, app/Services/NoovoCMSInterface.php, app/Services/NoovoCMSService.php, database/migrations/2021_12_03_072946_create_push_to_noovo_logs_table.php
Cur 2661 curriki noovo logging
=> Cur 2661 curriki noovo logging

app/Jobs/ExportProjecttoNoovo.php
=> Bugfix on logging

app/Services/NoovoCMSService.php
=> Fixed group file list path

app/Jobs/ExportProjecttoNoovo.php, app/Services/NoovoCMSService.php
=> update logging logic

app/Http/Controllers/Api/V1/StandAloneActivity.php, app/Http/Requests/V1/StandAloneActivityCreateRequest.php, app/Http/Resources/V1/StandAloneActivityResource.php, app/Models/Activity.php, app/Repositories/Activity/ActivityRepository.php, app/Repositories/Activity/ActivityRepositoryInterface.php, database/migrations/2021_12_08_474421_add_user_id_and_organization_id_to_activities_table.php, routes/api.php
RUN this migration: 
php artisan migrate --path=database/migrations/2021_12_08_474421_add_user_id_and_organization_id_to_activities_table.php
=> [CUR-2605] Initial code for stand alone interactive videos

app/Repositories/Project/ProjectRepository.php, php.ini
Resolve conflicts from merging staging to develop 14 dec 2021
=> Resolve conflicts from merging staging to develop 14 dec 2021

app/Http/Controllers/Api/V1/ProjectController.php, app/Repositories/Project/ProjectRepository.php, app/Repositories/Project/ProjectRepositoryInterface.php
[CUR-2495] Updated shared for playlists and activities on update of project shared
[CUR-2495]: https://curriki.atlassian.net/browse/CUR-2495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CUR-2495] Updated shared for playlists and activities on update of project shared

app/Repositories/Team/TeamRepository.php
=> fixed filelist name issue

app/Http/Controllers/Api/V1/SearchController.php, app/Repositories/Activity/ActivityRepository.php, app/Repositories/Activity/ActivityRepositoryInterface.php
Resolved issue with deep linking search
=> [CUR-2428} Resolved issue with deep linking search

app/Repositories/Team/TeamRepository.php
=> rename file name

app/Repositories/Activity/ActivityRepository.php
Resolved issue with deep linking search made user id optional
=> [CUR-2428] Resolved issue with deep linking search made user id optional

app/Console/Kernel.php
Configured cron using scheduler
=> Configured cron using scheduler

app/Repositories/Activity/ActivityRepository.php, database/seeds/AdvSearchSeeder.php
Resolved issue with search add check for deleted items
=> [CUR-2428] Resolved issue with search add check for deleted items

database/seeds/AdvSearchSeeder.php
Resolved issue with search function seeder
=> [CUR-2428] Resolved issue with search function seeder

app/Http/Resources/V1/SearchPostgreSqlResource.php, app/Http/Resources/V1/SearchResource.php, app/Repositories/Activity/ActivityRepository.php
Resolved issue with search, restored "SearchResource", added "SearchPostgreSqlResource".
=> CUR-2428: Replace Elastic Search_ Integrate Stored Procs

app/Http/Controllers/Api/V1/TeamController.php, app/Http/Requests/V1/TeamRequest.php, app/Http/Requests/V1/TeamUpdateRequest.php, app/Http/Resources/V1/TeamResource.php, app/Models/Team.php, app/Repositories/Team/TeamRepository.php
=> remove noovo-group id field

app/Http/Requests/V1/SuborganizationUpdate.php
fixed issue on update noovo client id
=> fixed issue on update noovo client id

app/Repositories/Team/TeamRepository.php
=> Remove .zip from file name

app/Console/Commands/deleteExportedProjects.php, app/Console/Kernel.php
Job to remove exported projects after x days
=> Job to remove exported projects after x days

app/Repositories/User/UserRepository.php
api work for search on exported project
=> api work for search on exported project

app/Http/Controllers/Api/V1/Integration/BrightcoveAPISettingsController.php, app/Http/Requests/V1/Integration/StoreBrightcoveAPISetting.php, app/Http/Requests/V1/Integration/UpdateBrightcoveAPISetting.php, app/Jobs/CloneBrightcoveAPISetting.php, app/Models/Integration/BrightcoveAPISetting.php, app/Repositories/Integration/BrightcoveAPISettingInterface.php, app/Repositories/Integration/BrightcoveAPISettingRepository.php, database/migrations/2021_12_22_130747_rename_eamil_column_in_brightcove_api_settings_table.php, resources/views/apidoc/index.blade.php, routes/api.php
Implement CRUD API for Brightcove Integration - Backend Work
=> Implement CRUD API for Brightcove Integration - Backend Work

database/seeds/DatabaseSeeder.php, database/seeds/OrganizationPermissionTypeUpdateSeeder.php
Created seeder to update "feature" for organization permissions.
=> CUR-2836: Created seeder to update "feature" for organization permissions.

app/Repositories/Activity/ActivityRepository.php, database/seeds/AdvSearchSeeder.php
Excluded standalone video activities from search.
=> CUR-2733: Excluded standalone video activities from search.

app/CurrikiGo/Brightcove/Videos/GetVideoList.php, app/Models/Integration/BrightcoveAPISetting.php
Quick fix for Brightcove Search API.
=> Quick fix for Brightcove Search API.

database/migrations/2022_01_11_105127_update_smentics_h5p__flashcards.php, database/seeds/H5PFlashCardLibSubmitButtonSeeder.php
Need to run Migration
php artisan migrate --path=database/migrations/2022_01_11_105127_update_smentics_h5p__flashcards.php
=> CUR-2856 Update Semantics to Add Submit Button

database/migrations/2022_01_11_111044_update_essay_semaintics_to_h5p_libraries.php, database/seeds/H5PEssaysLibSubmitButtonSeeder.php
Migration for essay submit button
=> Migration for essay submit button

database/seeds/H5PEssaysLibSubmitButtonSeeder.php
fixed issue on sementic seeder
=> fixed issue on sementic seeder

database/migrations/2022_01_11_160556_create_adv_search_functions_and_table.php
Added migration for adv search functions and table.
Removed AdvSearchSeeder.php
=> CUR-2428: Added migration for adv search functions and table.

database/seeds/H5PEssaysLibSubmitButtonSeeder.php, database/seeds/H5PFlashCardLibSubmitButtonSeeder.php
=> Deployment from Develop to Staging

app/Repositories/Organization/OrganizationRepository.php
Removed case sensitivity from admin organizations search.
=> CUR-2943: Removed case sensitivity from admin organizations search.

database/migrations/2022_01_13_161355_add_organization_admin_permission_types_seeder.php, database/migrations/2022_01_13_163559_add_organization_admin_panel_permission_types_seeder.php, database/seeds/OrganizationAdminPanelPermissionTypeSeeder.php
Created migrations and seeders for new admin panel permissions.
=> CUR-2428: Created migrations and seeders for new admin panel permissions.

database/migrations/2022_01_18_163836_add_organization_admin_project_permission_type_seeder.php, database/seeds/OrganizationAdminProjectPermissionTypeSeeder.php
Added organization admin view all project permission..
=> CUR-2628: Clean-up Permissions

app/Http/Controllers/Api/V1/StandAloneActivityController.php
Quick fix for delete youtbue my interactive video activity.
=> quick fix for delete youtube activity.

database/migrations/2022_01_19_113813_update_true_false_semantics_seeder.php, database/seeds/H5PTrueFalseSubmitButtonSeeder.php
seeder migration for true false semantics
=> seeder migration for true false semantics

app/Repositories/Project/ProjectRepositoryInterface.php
Remove indexing and statusUpdate methods from ProjectRepositoryInterface.
=> CUR-2952: API changes to reflect correct Project status

app/Http/Requests/V1/Integration/StoreBrightcoveAPISetting.php, app/Http/Requests/V1/Integration/UpdateBrightcoveAPISetting.php
Handle the account id, name and email unique validation for a specific organizations.
=> Handle unique validation with specific org.

database/migrations/2022_01_25_143605_create_migration_essay_semantic__changes.php, database/seeds/H5PEssaysLibSubmitButtonSeeder.php
=> Essay semantic changes

app/Repositories/Project/ProjectRepository.php
Merged master to staging branch and resolved conflicts.
=> Merged master to staging branch and resolved conflicts.

app/Repositories/LtiTool/LtiToolSettingRepository.php
Update query for kaltura lti tool settings.
=> Query update for kaltura lti tool settings.

app/Repositories/Organization/OrganizationRepository.php
=> CUR-3142: Spike for User deletion and associated tables

app/Http/Controllers/Api/V1/CurrikiInteractiveVideoIntegration/Kaltura/KalturaGeneratedAPIClientController.php, app/Repositories/LtiTool/LtiToolSettingInterface.php, app/Repositories/LtiTool/LtiToolSettingRepository.php
=> Get the logged user kaltura media list

app/Console/Commands/importProjects.php, app/Repositories/Project/ProjectRepository.php
hotfix for import command script changes
=> hotfix for import command script changes

app/Http/Controllers/Api/V1/CurrikiInteractiveVideoIntegration/Kaltura/KalturaGeneratedAPIClientController.php, app/Repositories/LtiTool/LtiToolSettingInterface.php, app/Repositories/LtiTool/LtiToolSettingRepository.php
=> Update Kaltura api functionality w.r.t org.

resources/views/apidoc/index.blade.php
=> API doc update for kaltura media list api

app/Repositories/Project/ProjectRepository.php
Resolved issue with reordering of my projects not working.
=> CUR-3247: Reorder projects is not working on My projects

database/migrations/2022_02_17_065607_update_questionnaire_semantics_to_h5p_libraries.php, database/seeds/H5PQuestionnaireSubmitButtonSeeder.php
Add submit button semantics for questionnaire
=> Add submit button semantics for questionnaire

app/Http/Controllers/Api/V1/ProjectController.php, app/Repositories/Project/ProjectRepository.php, app/Repositories/Project/ProjectRepositoryInterface.php
Refactored code to improve the performance of reordering my projects.
=> CUR-2259: Web response time > 5 seconds at least once in 5 minutes on /App\Http\Controllers\Api\V1\ProjectController@reorder

app/Http/Controllers/Api/V1/LtiTool/LtiToolSettingsController.php
Validation rule for clone feature.
=> Apply validation rule in case of clone.

routes/api.php
Reverts ActiveLearningStudio/ActiveLearningStudio-API#904
=> Revert "Bugfix - Unauthenticated error on search tab deeplink launch "

app/Http/Controllers/Api/V1/LtiTool/LtiToolSettingsController.php, app/Http/Requests/V1/LtiTool/StoreLtiToolSetting.php, app/Http/Requests/V1/LtiTool/UpdateLtiToolSetting.php
Update validation rule w.r.t user based.
=> Update validation rule w.r.t user id

database/migrations/2022_01_18_074324_seeder_for_arithmatic_quiz.php, database/migrations/2022_01_25_143605_create_migration_essay_semantic__changes.php, database/migrations/2022_02_17_065607_update_questionnaire_semantics_to_h5p_libraries.php
Fixed seeder execution issue on staging
=> Fixed seeder execution issue on staging

app/Http/Controllers/Api/V1/LtiTool/LtiToolSettingsController.php, app/Http/Requests/V1/LtiTool/StoreLtiToolSetting.php, app/Http/Requests/V1/LtiTool/UpdateLtiToolSetting.php
=> Hot fix for CUR-3269

app/Http/Controllers/Api/V1/ProjectController.php, app/Http/Requests/V1/ProjectUpdateOrder.php, app/Policies/ProjectPolicy.php, app/Repositories/Project/ProjectRepository.php, app/Repositories/Project/ProjectRepositoryInterface.php, routes/api.php
Added form requests check for project update order.
Updated create project to increment order of existing projects before creating new with order 1.
Added new route with logic for reordering project.
=> CUR-2259: Optimized project reordering

app/Repositories/Project/ProjectRepository.php
Update code to start project order from zero.
=> CUR-2259: Update code to start project order from zero.

app/Http/Controllers/Api/V1/CurrikiInteractiveVideoIntegration/Kaltura/KalturaGeneratedAPIClientController.php
Resolve Kaltura entitlement or privacy context issue for media list.
=> Fix kaltura privacy context issue for media

database/migrations/2022_03_03_104952_seeder_update_semantic_immersive_reader_h5p.php, database/migrations/2022_03_03_105831_seeder_add_semantic_immersive_reader_editor_h5p.php, database/migrations/2022_03_03_112558_seeder_add_semantic_star_rating_h5p.php, database/migrations/2022_03_08_105017_add_bright_cove_h5p_library.php, database/migrations/2022_03_08_105129_add_bright_cove_editor_h5p_library.php, database/migrations/2022_03_08_110936_add_h5p_curriki_interactive_video_h5p.php, database/migrations/2022_03_08_112009_update_semantic_open_end_question_h5p.php, database/seeds/H5PBrightCoveEditorLibrarySeeder.php, database/seeds/H5PBrightCoveLibrarySeeder.php, database/seeds/H5PImmersiveReaderEditorSemanticSeeder.php, database/seeds/H5PImmersiveReaderSemanticSeeder.php, database/seeds/H5PStarRatingSeeder.php, database/seeds/H5pCurrikiInteractiveVideoSeeder.php, database/seeds/UpdateSemanticOpenEndQuestionSeeder.php
Added migrations for missing libraries
=> Added migrations for missing libraries

database/migrations/2022_03_08_165716_reorder_user_org_projects_in_default_order_seeder_migration.php, database/seeds/ReorderUserOrgProjectsInDefaultOrderSeeder.php
Created migration and seeder for reordering user organization projects in default order..
=> CUR-3327: My Projects tab: The reordered project location appears always plus 1 unit

app/Http/Controllers/Api/V1/CurrikiInteractiveVideoIntegration/Kaltura/KalturaGeneratedAPIClientController.php
=> Update kaltura privileges.

app/Console/Kernel.php, app/Jobs/ExportProjecttoNoovo.php
=> Add route for Noovo Publish

app/Http/Controllers/Api/V1/CurrikiInteractiveVideoIntegration/Kaltura/KalturaGeneratedAPIClientController.php
Update Kaltura media privileges.
=> Update Kaltura Privileges

database/migrations/2022_03_16_080542_update_bright_cove_h5p_library_seeder.php, database/seeds/H5PBrightCoveLibrarySeeder.php
Fixed brightCove Library seeder
=> Fixed brightCove Library seeder

database/migrations/2022_02_01_080228_remove_search_project_export_import_organization_permission_types_table.php
Added "--force => true" to migration.
=> CUR-3133: Permissions related observations

app/Http/Controllers/Api/V1/ProjectController.php, app/Repositories/Activity/ActivityRepository.php
Fixed issue of editor images missing on project import
=> Fixed issue of editor images missing on project import

app/Http/Requests/V1/LtiTool/StoreLtiToolSetting.php, app/Http/Requests/V1/LtiTool/UpdateLtiToolSetting.php
Update lti tool settings table.
=> Update tool type column to lti tool settings table

database/migrations/2022_03_24_161828_add_force_to_organization_admin_project_permission_type_seeder.php
Hotfix to force organization_admin_project_permission_type_seeder on develop.
=> Hotfix to force organization_admin_project_permission_type_seeder on develop.

database/migrations/2022_03_24_161431_add_force_to_organization_admin_project_permission_type_seeder.php
Hotfix to force organization_admin_project_permission_type_seeder on staging.
=> Hotfix to force organization_admin_project_permission_type_seeder on staging.

app/Console/Kernel.php, app/Http/Controllers/Api/V1/TeamController.php, app/Jobs/ExportProjecttoNoovo.php, app/Repositories/CurrikiGo/LmsSetting/LmsSettingRepository.php, app/Repositories/CurrikiGo/LmsSetting/LmsSettingRepositoryInterface.php, routes/api.php
Change noovo logic on project level
=> Change noovo logic on project level

database/migrations/2022_03_24_153949_add_force_to_organization_admin_project_permission_type_seeder.php
Hotfix to force organization_admin_project_permission_type_seeder on master.
=> Hotfix to force organization_admin_project_permission_type_seeder on master.

database/migrations/2022_03_28_112742_update_question_set_semantic_to_create_curriki_settings.php, database/seeds/H5PQuestionSetLibSubmitButtonSeeder.php
Seeder to update Question set semantic
=> Seeder to update Question set semantic

app/Http/Controllers/Api/V1/UserController.php, routes/api.php
Change Auth logic for download export
=> Change Auth logic for download export

app/Http/Controllers/Api/V1/CkEditorFileManagerController.php
=> change field name

app/Http/Controllers/Api/V1/CkEditorFileManagerController.php
=> Change Upload file logic

app/Http/Controllers/Api/V1/CkEditorFileManagerController.php
=> Fixed url issue

app/Http/Controllers/Api/V1/ActivityItemController.php, app/Http/Controllers/Api/V1/ActivityTypeController.php, app/Http/Requests/V1/StoreActivityItem.php, app/Http/Requests/V1/StoreActivityType.php, app/Http/Requests/V1/UpdateActivityItem.php, app/Http/Requests/V1/UpdateActivityType.php, app/Http/Resources/V1/ActivityItemResource.php, app/Http/Resources/V1/ActivityTypeResource.php, app/Models/ActivityItem.php, app/Models/ActivityType.php, app/Repositories/ActivityItem/ActivityItemRepository.php, app/Repositories/ActivityItem/ActivityItemRepositoryInterface.php, app/Repositories/ActivityType/ActivityTypeRepository.php, app/Repositories/ActivityType/ActivityTypeRepositoryInterface.php, routes/api.php
Reverts ActiveLearningStudio/ActiveLearningStudio-API#1002
=> Revert "[CUR-3260] manage activity type and items organization specific"

app/Http/Controllers/Api/V1/ActivityItemController.php, app/Http/Controllers/Api/V1/ActivityTypeController.php, app/Http/Requests/V1/StoreActivityItem.php, app/Http/Requests/V1/StoreActivityType.php, app/Http/Requests/V1/UpdateActivityItem.php, app/Http/Requests/V1/UpdateActivityType.php, app/Http/Resources/V1/ActivityItemResource.php, app/Http/Resources/V1/ActivityTypeResource.php, app/Models/ActivityItem.php, app/Models/ActivityType.php, app/Repositories/ActivityItem/ActivityItemRepository.php, app/Repositories/ActivityItem/ActivityItemRepositoryInterface.php, app/Repositories/ActivityType/ActivityTypeRepository.php, app/Repositories/ActivityType/ActivityTypeRepositoryInterface.php, routes/api.php
Reverts ActiveLearningStudio/ActiveLearningStudio-API#1003
=> Revert "Revert "[CUR-3260] manage activity type and items organization specific""

app/Http/Controllers/Api/V1/CkEditorFileManagerController.php
=> Add filetype check

app/CurrikiGo/Brightcove/Commands/GetAPITokenCommand.php
=> Fix content type header issue

app/Http/Controllers/Api/V1/TeamController.php, app/Repositories/CurrikiGo/LmsSetting/LmsSettingRepository.php
fixed the issue of subject-education-level on noovo push
=> fixed the issue of subject-education-level on noovo push

app/Http/Controllers/Api/V1/UserController.php, app/Http/Requests/V1/SuborganizationAddNewUser.php
implemented add users to multiple organizations
=> [CUR-3635] add user to multi organizations

app/CurrikiGo/Moodle/Playlist.php, app/Repositories/Activity/ActivityRepository.php, app/Repositories/CurrikiGo/LmsSetting/LmsSettingRepository.php, app/Repositories/Project/ProjectRepository.php
=> Fixed grade Pass back issues

app/CurrikiGo/Moodle/Playlist.php, app/Repositories/CurrikiGo/LmsSetting/LmsSettingRepository.php, app/Repositories/Project/ProjectRepository.php
=> fixed team id issue

app/Repositories/Activity/ActivityRepository.php
Fixed issue on import- export feature
=> Fixed issue on import- export feature

app/Http/Controllers/Api/V1/Integration/BrightcoveAPISettingsController.php, app/Repositories/Integration/BrightcoveAPISettingRepository.php
=> Resolve brightcove sql issue.

app/Repositories/Activity/ActivityRepository.php, app/Repositories/EducationLevel/EducationLevelRepository.php, app/Repositories/EducationLevel/EducationLevelRepositoryInterface.php, app/Repositories/Subject/SubjectRepository.php, app/Repositories/Subject/SubjectRepositoryInterface.php
Updated search, for subject and education level filter, match with name instead of ids.
=> CUR-3658  Modify Search: Some mistakes about UI, function

app/Repositories/Organization/OrganizationRepository.php
get activity type ID for its items  from the newly created activity type, not from the parent activity type
=> [CUR-3671] Fixed duplication issue of activity items

app/Http/Controllers/Api/V1/IndependentActivityController.php, app/Http/Requests/V1/OrganizationIndependentActivityRequest.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php, app/Repositories/IndependentActivity/IndependentActivityRepositoryInterface.php, routes/api.php
Added the feature to list independent activities in admin panel.
Added the feature to view independent activities for "Library request to review".
Added the feature to search independent activities by title and user email.
Added the feature to filter independent activities by author, created and updated dates, library and shared statues.
Added the feature to paginate and set rows per page.
=> CUR-3485: As an Admin I can perform all of the same functions on an Independent Activity I perform on a project.

app/Http/Controllers/Api/V1/Integration/VideoDirectUrlController.php, database/migrations/2022_05_19_110208_update_h5p_video_library_file_to_h5p_libraries_table.php, database/seeds/UpdateH5PVideoLibraryFileSeeder.php, routes/integrations.php
Implement the direct URL functionality for Vimeo and Komodo video integration.
=> Implement the direct Url functionality for Vimeo and Komodo.

app/Http/Controllers/Api/V1/IndependentActivityController.php, app/Http/Controllers/Api/V1/UserController.php, app/Http/Resources/V1/ExportedIndependentActivitiesResource.php, app/Jobs/ExportIndependentActivity.php, app/Notifications/ActivityExportNotification.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, database/migrations/2022_05_23_092300_add_org_id_notification_table.php, routes/api.php
=> Add org details

app/Http/Controllers/Api/V1/IndependentActivityController.php, app/Jobs/CopyIndependentActivityIntoPlaylist.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php, app/Repositories/IndependentActivity/IndependentActivityRepositoryInterface.php, routes/api.php
Add feature copy into playlist
=> Add feature copy into playlist

app/Http/Controllers/Api/V1/ProjectController.php, app/Http/Controllers/Api/V1/UserController.php, app/Jobs/ExportProject.php, app/Notifications/ProjectExportNotification.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, database/migrations/2022_05_30_071507_add_org_id_in_notification_table_for_project_notification.php, routes/api.php
Add org check on exported project list
=> Add org check on exported project list

app/Http/Controllers/Api/V1/IndependentActivityController.php, app/Jobs/ExportIndependentActivity.php, database/migrations/2022_05_23_092300_add_org_id_notification_table.php
Fixed issues on independent activity export list
=> Fixed issues on independent activity export list

app/Console/Kernel.php
Fixed bug on delete exported project cron
=> Fixed bug on delete exported project cron

app/Repositories/IndependentActivity/IndependentActivityRepository.php
Associated duplicated independent activity with user, organization and private visibility.
=> CUR-3773: Independent Activity Duplication not appear on search 

app/Http/Controllers/Api/V1/SearchController.php, app/Http/Requests/V1/SearchIndependentActivityRequest.php, app/Http/Resources/V1/SearchIndependentActivityResource.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php, database/migrations/2022_06_12_212952_create_independent_activities_adv_search_functions_and_table.php, routes/api.php, storage/responses/search/independent-activities.json
Search API for independent activities
=> CUR-3483: Search API for independent activities

app/Http/Controllers/Api/V1/UserController.php, storage/responses/notifications/export-notifications.json, storage/responses/notifications/independent-activity-export-notifications.json
=> Add json response files

H5P/laravel-h5p/src/LaravelH5p/Http/Controllers/AjaxController.php
=> Validate field param

app/Repositories/ActivityItem/ActivityItemRepository.php, database/migrations/2022_06_22_400000_update_activity_items_order.php, database/migrations/2022_06_22_500000_update_activity_layouts_descriptions.php, database/seeds/UpdateActivityItemsOrderSeeder.php, database/seeds/UpdateActivityLayoutsDescriptionSeeder.php
- Have made all activity Items order # = 100
- Updated the Layout Descriptions. Got a description from the corresponding Activity item.
- Have fixed activity items ordering in query
=> [CUR-3833] updated layouts descriptions and update the order of items to 100

app/Repositories/Playlist/PlaylistRepository.php, app/Repositories/Project/ProjectRepository.php
Fixed order issues of activities when we preview
=> [CUR-3834] Activity order issue

app/Http/Requests/V1/IndependentActivityEditRequest.php
fixed indepenedent activity update content issue
=> fixed indepenedent activity update content issue

app/Http/Controllers/Api/V1/CurrikiInteractiveVideoIntegration/Kaltura/KalturaGeneratedAPIClientController.php, app/Http/Controllers/Api/V1/Integration/VimeoAPIClientController.php, app/Repositories/LtiTool/LtiToolSettingRepository.php, app/helpers.php
Update Kaltura and Vimeo functionality.
=> Update kaltura and vimeo functionality w.r.t org specific video sources.

app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php
Cherry picked commits for CUR-3863
=> CUR-3863 - Removing Canvas API token dependency

app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php
CUR-3863 - Removing Canvas API token dependency
Conflicts resolved.
=> Cherrypick CUR-3863 into Production from Staging.

app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php
from ActiveLearningStudio/cherrypick-lti-fix-20220705"
This reverts commit 6e16dbae1c28e3d8b876bf18011164d9930d3681.
=> Revert "Merge pull request #1180

app/Repositories/Project/ProjectRepository.php
Updated logic for create project to create a default playlist on creation of project.
=> CUR-3903  Backend work to create sample playlist when a new project is created

app/Repositories/IndependentActivity/IndependentActivityRepository.php
Resolved issue with subjects and educational level search in independent activities.
=> CUR-3906   Unable to perform Advanced Search from Activities

database/migrations/2022_07_14_113014_update_civ_semantics_functionality_to_h5p_libraries_table.php, database/seeds/UpdateCIVSemanticsFunctionalityToH5PLibrariesSeeder.php
Implement seed to update semantics functionality.
=> Implement seed to update the semantics for CIV.

app/Http/Resources/V1/ProjectResource.php
Added playlists in user projects listing response.
=> CUR-3903: Backend work to create sample playlist when a new project is created

database/migrations/2022_07_21_105100_update_independent_activities_adv_search_functions_and_table.php
Resolved issue with migrations, deleted old search functions.
Integrated updated independent activities advance search functions.
=> CUR-3906: Unable to perform Advanced Search from Activities

database/migrations/2022_07_26_091019_update_adv_search_functions_and_table.php
Integrated scripts to resolve issue with non matching projects, playlists on search by subject, education level.
=> CUR-3896: Backend: Improve Search

app/Http/Controllers/Api/V1/IndependentActivityController.php
Updated the create independent activity function to return the default values for model attributes instead of null.
=> CUR-3908: Backend: Library Preference API Work

app/Http/Controllers/Api/V1/IndependentActivityController.php, app/Http/Requests/V1/MoveIndependentActivityIntoPlaylistRequest.php
Added validation to make sure any activities that are moving to projects have share disabled and Library Preference is Private.
=> CUR-3489: As an author, I can move an Independent Activity into a playlist that is part of a project.

app/Repositories/Project/ProjectRepository.php
Resolved the issue with project search showing other users projects as well.
=> CUR-3847: Lazy load My Projects and Search

database/migrations/2022_07_29_112950_create_performance_optimization_indexes.php
Added migration for creating performance optimization indexes.
=> CUR-3921: Investigate Backend Incidents and make recomendations to address

database/migrations/2022_08_01_092817_update_media_sources_table.php, database/seeds/UpdateMediaSourceSeeder.php
=> Add Komodo video option into media_sources table.

app/Repositories/IndependentActivity/IndependentActivityRepository.php, app/helpers.php
=> Fixed issues on thumbnail

app/Repositories/IndependentActivity/IndependentActivityRepository.php
Fixed import issue in independent activities
=> Fixed import issue in independent activities

app/Repositories/IndependentActivity/IndependentActivityRepository.php
=> fixed thumbnail issue

app/Http/Controllers/Api/V1/LtiTool/LtiToolSettingsController.php, app/Repositories/LtiTool/LtiToolSettingRepository.php
Update the Lti tool settings functionality.
=> Update get list api

app/Http/Controllers/Api/V1/IndependentActivityController.php, app/Http/Controllers/Api/V1/ProjectController.php, app/Policies/IndependentActivityPolicy.php, app/Policies/ProjectPolicy.php
Added separate admin and author permissions for projects and independent activities.
=> CUR-3468: Independent Activities

app/Http/Controllers/Api/V1/LtiTool/LtiToolSettingsController.php, app/Repositories/LtiTool/LtiToolSettingRepository.php
Update lti tool settings clone API.
=> Fix the clone api issue for lti tool settings.

database/migrations/2022_08_05_754680_upgrade_h5p_versions.php, database/seeds/UpgradeH5pVersionsSeeder.php
2. Update Demo activity id & video url for Branching Scenario
=> 1. Update H5P Library versions in Activity Layout & Activity Items

database/migrations/2022_01_18_074324_seeder_for_arithmatic_quiz.php, database/migrations/2022_01_25_143605_create_migration_essay_semantic__changes.php, database/migrations/2022_02_09_100506_seeder_update_true_false_semantics.php, database/migrations/2022_02_17_065607_update_questionnaire_semantics_to_h5p_libraries.php, jenkins/Jenkinsfile.api
Hotfix/ add force on seeders migrations - develop
=> Hotfix/ add force on seeders migrations - develop

app/Repositories/Activity/ActivityRepository.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php
Resolved negative query issue on project and independent activity search.
=> CUR-3971: Explore Library: Search results disappear when entering words that are not related to results in the "Does not contain" text box

app/Repositories/Activity/ActivityRepository.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php
Resolved case sensitivity issue with negative query search.
=> CUR-3971  Explore Library: Search results disappear when entering words that are not related to results in the "Does not contain" text box

app/Http/Controllers/Api/V1/TeamController.php, app/Repositories/CurrikiGo/LmsSetting/LmsSettingRepository.php, app/Repositories/Team/TeamRepository.php, app/Repositories/Team/TeamRepositoryInterface.php
CUR-4042-fix-publish-to-satellite-issue
=> CUR-4042-fix-publish-to-satellite-issue

app/Repositories/LtiTool/LtiToolSettingRepository.php
Set the lti tool settings record as descending by default.
=> CUR-4053 - Set the lti tool settings record as descending by default.

app/Repositories/Activity/ActivityRepository.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php
Made "Author" search case insensitive for independent activity and project search.
=> CUR-4092: Make "Author" search case insensitive

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Providers/RepositoryServiceProvider.php, app/Repositories/Organization/OrganizationRepository.php, app/Repositories/OrganizationRoleType/OrganizationRoleTypeRepository.php, app/Repositories/OrganizationRoleType/OrganizationRoleTypeRepositoryInterface.php
Resolved issue with mapping ui permissions to backend permissions. Refactored code to improve quality, created "OrganizationRoleType" repository.
=> CUR-3978: Permissions should have a DB table to map UI Permissions to API permissions

app/Http/Controllers/Api/V1/MicroSoftTeamController.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepository.php
=> CUR-4066 add checks

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Resources/V1/UiModulePermissionResource.php, app/Http/Resources/V1/UiModuleResource.php, app/Http/Resources/V1/UiSubModuleResource.php
CUR-4105 updated UI permissions scenarios to select a parent option
=> CUR-4105 updated UI permissions scenarios

app/Repositories/MicrosoftTeam/MicrosoftTeamRepository.php
CUR-4054 - Fixed issue of link in assignment
=> CUR-4054 - Fixed issue of link in assignment

app/Models/IndependentActivity.php, database/migrations/2022_09_21_102544_update_activities_table_and_columns_addition.php, database/migrations/2022_09_21_161808_drop_indp-activities_tables.php
initial commit 4136, migrations added
=> CUR-4136 Database change for table "Activities"

database/migrations/2022_09_28_120628_update_adv_search_functions_and_table.php
Integrated niket script for project search.
=> CUR-4165  Search query changes

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Requests/V1/SuborganizationSave.php, app/Http/Requests/V1/SuborganizationUpdate.php, app/Http/Resources/V1/OrganizationResource.php, app/Models/Organization.php, database/migrations/2022_09_28_091939_add_ms_team_app_keys_to_organizations_table.php, storage/responses/organization/suborganization.json
CUR-4179 add ms teams fileds in organizations
=> CUR-4179 add ms teams fileds in organizations

database/migrations/2022_09_29_073919_update_independent_activities_adv_search_functions_and_table.php
Integrated Niket script for independent activity search.
=> CUR-4165: Search query changes

app/Repositories/Activity/ActivityRepository.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php
- Fixed "description" issue of independent activity in cloned activity. 
- Fixed deletion issue of Copied interactive video.
=> CUR-4197 Fixed some reported issues

app/Http/Controllers/Api/V1/SearchController.php, app/Http/Requests/V1/SearchIndependentActivityRequest.php, app/Http/Requests/V1/SearchRequest.php, app/Repositories/Activity/ActivityRepository.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php
Updated search for LTI to also show users private projects and independent activities by adding "searchType" for "lti_search".
=> CUR-4228: Update search for LTI to also show user's private projects and independent activities

database/migrations/2022_09_29_073919_update_independent_activities_adv_search_functions_and_table.php
=> CUR 4133 conflict resolve with staging

database/migrations/2022_10_06_073919_update_independent_activities_adv_search_functions_and_table.php, database/migrations/2022_10_06_120628_update_adv_search_functions_and_table.php
Restored the project and independent activity search scripts in staging from 4133 branch to resolve conflicts issues.
=> CUR-4133: Implement 'independent' activities data can be segregated from 'activities' data

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Http/Requests/V1/ClassRoomIntegrationRequest.php, app/Http/Requests/V1/SuborganizationSave.php, app/Http/Requests/V1/SuborganizationUpdate.php, routes/api.php
CUR-4255 - Added feature to update google classroom and ms team data
=> CUR-4255 - Added feature to update google classroom and ms team data

Dockerfile.cron, LICENSE, app/Console/Commands/MoveIndependentActivitiesToActivities.php, app/Http/Controllers/Api/V1/CurrikiGo/ExtractXAPIJSONController.php, app/Http/Controllers/Api/V1/GoogleClassroomController.php, app/Http/Controllers/Api/V1/SearchController.php, app/Http/Requests/V1/MoveIndependentActivityIntoPlaylistRequest.php, app/Http/Requests/V1/SearchIndependentActivityRequest.php, app/Http/Requests/V1/SearchRequest.php, app/Http/Resources/V1/ActivityResource.php, app/Http/Resources/V1/IndependentActivityResource.php, app/Http/Resources/V1/StandAloneActivityResource.php, app/Models/Activity.php, app/Models/IndependentActivity.php, app/Models/Playlist.php, app/Repositories/Activity/ActivityRepository.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php, app/helpers.php, config/constants.php, database/migrations/2022_09_21_102544_update_activities_table_and_columns_addition.php, database/migrations/2022_09_27_091300_run_seeder_for_activity_type.php, database/migrations/2022_10_06_073919_update_independent_activities_adv_search_functions_and_table.php, database/migrations/2022_10_06_120628_update_adv_search_functions_and_table.php, database/migrations/2022_10_12_062631_create_outcome_data_view.php, database/seeds/ActivityTypesToExistingData.php, entrypoint.cron.sh, site.conf
Independent activities, as well as migrations.
=> Merge Staging into Develop

database/migrations/2022_10_19_073919_update_independent_activities_adv_search_functions_and_table.php, database/migrations/2022_10_19_120628_update_adv_search_functions_and_table.php
Integrated SQL scripts for independent activity and project search.
=> CUR-4068: Combination of filters do not work on Projects -search

app/Http/Controllers/Api/V1/CurrikiInteractiveVideoIntegration/Kaltura/KalturaGeneratedAPIClientController.php
CUR-4267 Resolve spell mistake issue.
=> Bugfix/CUR-4267 spell mistake Kaltura API

app/Repositories/Activity/ActivityRepository.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php, database/migrations/2022_10_31_073919_update_independent_activities_adv_search_functions_and_table.php, database/migrations/2022_10_31_120628_update_adv_search_functions_and_table.php
Integrated the updated scripts for LMS, independent activity and project search. 
Resolved the issue with search by multiple activity types. 
Added the feature to filter on activity type version as well.
=> CUR-4328: Fix filter for existing search

app/Console/Commands/EliminateDualSignups.php, app/Jobs/EliminateDualSignupJob.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, app/User.php
Eliminate the dual signups and swap the id's
=> CUR 4330 eliminate dual signup and swap the ids

app/Http/Controllers/Auth/AuthController.php
=> CUR 4323 case insensitivity property added

app/Http/Controllers/Auth/AuthController.php
Cur 4323 issue fixed in SSO API
=> Cur 4323 issue fixed in SSO API

app/Http/Controllers/Api/V1/LtiTool/LtiToolSettingsController.php, app/Http/Controllers/Api/V1/SuborganizationController.php, app/Models/Organization.php, database/migrations/2022_11_01_111337_add_lti_tool_settings_status_organization_media_sources_table.php, database/migrations/2022_11_01_125157_update_lti_tool_settings_status_to_organization_media_sources_table.php, database/seeds/UpdateLtiToolSettingsStatusToOrganizationMediaSourcesSeeder.php, storage/responses/organization/filter-media-source.json
CUR-4351 Update org specific media sources functionality w.r.t LTI Tool Settings.
=> CUR-4351 Update org specific media sources functionality w.r.t LTI Tool Settings.

app/Http/Controllers/Api/V1/LtiTool/LtiToolSettingsController.php
CUR-4354 Quick fix get lti tool type functionality for LTI Tool settings.
=> CUR-4354 Quick fix get lti tool type functionality for LTI Tool settings.

app/Console/Commands/EliminateDualSignups.php, app/Http/Controllers/Api/V1/CurrikiGo/ExtractXAPIJSONController.php, app/Http/Controllers/Auth/AuthController.php, app/Jobs/EliminateDualSignupJob.php, app/Repositories/User/UserRepository.php, app/Repositories/User/UserRepositoryInterface.php, app/User.php, database/seeds/UpdateActivityItemTitleSeeder.php
Merged "staging" branch to "develop" and resolved conflicts.
=> CUR-4361: Merge "master" branch to "staging", then "staging" to "develop"

tests/Feature/ExampleTest.php, tests/Unit/PlaylistTest.php, tests/Unit/ProjectTest.php
=> CUR-4337-fixed url issue

app/Http/Requests/V1/LtiTool/KalturaAPISettingRequest.php, app/Http/Requests/V1/LtiTool/KomodoAPISettingRequest.php, app/Http/Requests/V1/LtiTool/VimeoAPISettingRequest.php
CUR-4366 update validation rule.
=> CUR-4366 update validation rule.

database/migrations/2022_11_16_115028_remove_komodo_option_to_organization_media_sources_table.php, database/seeds/RemoveKomodoOptionToOrganizationMediaSourcesSeeder.php
CUR-4406 Seeder to un-check the Komodo media sources.
=> CUR-4406 Seeder to un-check the Komodo media sources.

database/migrations/2022_11_17_122441_upgrade-h5p-libraries.php, database/seeds/UpgradeH5pLibrariesVersionsSeeder.php, database/seeds/upgradeH5pLibrariesSeeder.php
We have upgraded H5P libraries but we haven't linked those libraries with the layouts/items within the database. So I'm going to create a seeder for library linking.
=> [CUR-4415] Link upgraded activities with layouts/items in database

database/migrations/2022_11_18_100000_default_allowed_visibility_types.php, database/seeds/DefaultAllowedVisibilityTypesSeeder.php
Assigned default allowed visibility types to all existing orgs
=> [CUR-4426] assigned default allowed visibility types to all existing orgs

app/Http/Controllers/Api/V1/MicroSoftTeamController.php, app/Jobs/PublishPlaylist.php, app/Notifications/PlaylistPublishNotification.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepository.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepositoryInterface.php, routes/api.php
CUR-4186-publish playlist in ms teams
=> CUR-4186-publish playlist in ms teams

app/Http/Controllers/Api/V1/LtiTool/LtiToolSettingsController.php
CUR-4404 Update lti duplicate record message.
=> CUR-4404 Update lti duplicate record message.

app/CurrikiGo/Komodo/Client.php, app/CurrikiGo/Komodo/Commands/Videos/GetMyVideoListCommand.php, app/CurrikiGo/Komodo/Videos/GetMyVideoList.php, app/Http/Controllers/Api/V1/Integration/KomodoAPIClientController.php, config/komodo.php
CUR-4439 Update komodo api wrt logged user email.
=> CUR-4439 Update komodo api wrt logged user email.

app/Http/Controllers/Api/V1/LtiTool/LtiToolSettingsController.php, app/Http/Requests/V1/LtiTool/StoreLtiToolSettingRequest.php, app/Http/Requests/V1/LtiTool/UpdateLtiToolSettingRequest.php
CUR-4462 update validation request for media sources w.r.t org.
=> CUR-4462 update validation request for media sources w.r.t org.

app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php, app/Repositories/CurrikiGo/LmsSetting/LmsSettingRepository.php, app/Repositories/CurrikiGo/LmsSetting/LmsSettingRepositoryInterface.php
add email clause in lms settings query
=> CUR 4479 add email clause in lms settings query

app/helpers.php
CUR-4473-Fixed the issue on project duplicate
=> CUR-4473-Fixed the issue on project duplicate

app/Http/Controllers/Api/V1/SuborganizationController.php
CUR-4492 Update media sources success message.
=> CUR-4492 Update media sources success message.

composer.json
CUR-4482 change package placement
=> CUR-4482 change package placement

app/Repositories/IndependentActivity/IndependentActivityRepository.php, app/Repositories/User/UserRepository.php
Fixed staging post release issues
=> Fixed staging post release issues

app/Http/Controllers/Api/V1/SuborganizationController.php, app/Models/OrganizationVisibilityType.php, database/migrations/2022_12_08_154356_default_allowed_visibility_types.php, database/migrations/2022_12_08_154703_run_update_allowed_organization_visibility_types_seeder.php, database/seeds/DefaultAllowedVisibilityTypesSeeder.php, database/seeds/OrganizationVisibilityTypeSeeder.php, database/seeds/UpdateAllowedOrganizationVisibilityTypesSeeder.php
Updated the display name for "global" visibility to "My Organization". 
Updated the display name for "protected" visibility to "Protected". 
Set the default allowed organization visibility types to "private", "global" and "public".
=> CUR-4123: Library Preference Enhancements

database/migrations/2022_12_13_123517_h5p_branching_question_editor.php, database/seeds/H5pBranchingQuestionEditor.php, database/seeds/H5pBranchingQuestionEditorSeeder.php
Branching Scenario Editor > Branching Question has "Missing translations for library H5PEditor.BranchingQuestion" 
added the languages in seeder
=> [CUR-4466] added the library language

app/Http/Controllers/Api/V1/IndependentActivityController.php
Applied export permission to download xAPI format
=> [CUR-4501] Applied export permission to download xAPI format

database/migrations/2022_12_16_094203_update_drag_question_semantics.php, database/seeders/H5PDragQuestionsUpdateSemanticsSeeder.php
CUR-4465 Fixed issue of duplicate show title on drag question
=> CUR-4465 Fixed issue of duplicate show title on drag question

app/Repositories/Organization/OrganizationRepository.php
Have applied users search by first name and last name with case insensitive.
=> [CUR-4514] Fixed users search issues

app/Repositories/LtiTool/LtiToolSettingRepository.php
CUR-4538 remove user from lti list search.
=> CUR-4538 remove user from lti list search.

app/Repositories/CurrikiGo/Outcome/OutcomeRepository.php, config/constants.php
altered a minor php code to fetch actor id
=> altered a minor php code to fetch actor id

app/Http/Controllers/Api/V1/IndependentActivityController.php, app/Http/Controllers/Api/V1/ProjectController.php, app/Http/Requests/V1/IndependentActivityEditRequest.php, app/Http/Requests/V1/ProjectUpdateRequest.php, app/Http/Requests/V1/SuborganizationSave.php, app/Http/Requests/V1/SuborganizationUpdate.php, app/Http/Resources/V1/OrganizationResource.php, app/Models/Organization.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php, app/Repositories/Project/ProjectRepository.php, database/migrations/2023_01_09_100000_add_auto_approve_to_organization_table.php
Implemented auto approve feature for my activities and projects.
=> [CUR-4552] Implemented auto approve feature

app/Repositories/CurrikiGo/Outcome/OutcomeRepository.php
Feature/cur 4557 alter summary page data fetch api
=> else added

app/Http/Requests/V1/SuborganizationSave.php, app/Http/Requests/V1/SuborganizationUpdate.php, app/Http/Resources/V1/OrganizationResource.php, app/Models/Organization.php, database/migrations/2023_01_10_120000_add_activity_title_format_to_organization_table.php
Added activity title formats from the admin panel
=> [CUR-4563] Activity title formats

app/Http/Controllers/Api/V1/IndependentActivityController.php
Remove xAPI permission from backend
=> [CUR-4570] Remove xAPI permission

database/seeders/UpdateAllowedOrganizationVisibilityTypesSeeder.php
Resolved issue with "UpdateAllowedOrganizationVisibilityTypesSeeder".
=> CUR-4463   Upgrade to Laravel 9.0

Dockerfile.cron.8.1
Merged master to staging resolved conflicts.
=> Merged master to staging resolved conflicts.

database/migrations/2023_01_16_104617_update_semantics_course_presentation.php, database/seeders/UpdateCoursePresentationSemanticsSeeder.php
CUR-4464-update course presentation semantics
=> CUR-4464-update course presentation semantics

app/Repositories/Organization/OrganizationRepository.php
Have fixed user search issue on admin panel
=> [CUR-4585] User search issue admin panel

app/Http/Controllers/Api/V1/MicroSoftTeamController.php, app/Http/Requests/V1/SubmitAssignmentMst.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepository.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepositoryInterface.php, routes/api.php
API to change status of an assignment is complete
=> API to change status of an assignment is complete

app/Repositories/Project/ProjectRepository.php
=> team id clause added

app/Policies/ProjectPolicy.php
Activity Preview Throw 500 Error
=> [CUR-4595] Activity Preview Issue on Stage

config/ms-team-configs.php
=> scope for refresh token added

app/Http/Controllers/Api/V1/CurrikiGo/ExtractXAPIJSONController.php, app/Models/GoogleClassroom.php
=> added a global force property

app/Http/Controllers/Api/V1/CurrikiGo/ExtractXAPIJSONController.php, app/Models/GoogleClassroom.php
=> lowercase teacher email fix

Package/opigno/tincan/src/Score.php
Framework Consulting/ Curriki Instructure:  Xapi statement value must be greater than 'min' (0) [0]
=> [CUR-4636] fixed the score exception

database/migrations/2023_02_13_144534_upgrade_h5_p_three_image.php, database/migrations/2023_02_15_094406_h5p_three_image_update.php, database/migrations/2023_02_15_121045_h5p_editor_three_image_update.php, database/migrations/2023_02_16_052731_h5p_upgrade_three_image_version.php, database/seeders/H5pEditorThreeImageUpdateSeeder.php, database/seeders/H5pUpgradeThreeImageVersionSeeder.php, database/seeders/UpgradeH5PThreeImageSeeder.php
Upgrade ThreeImage H5P library
=> [CUR-4643] Virtual Tour Broken

app/Http/Requests/V1/GetTokenViaCode.php
removed unnecessary validation
=> removed unnecessary validation

app/Http/Controllers/Api/V1/H5pController.php
API for saving the Buttons configuration
=> [CUR-4649] h5p display settings configuration

app/Http/Controllers/Api/V1/H5pController.php, app/Http/Resources/V1/OrganizationResource.php, app/Models/Organization.php, database/migrations/2023_02_22_103441_alter_organization_table.php
Added reuse and embed option feature in Organization
=> [CUR-4649] Added reuse and embed option feature

database/migrations/2023_02_27_102625_remove_document_embeder_library.php, database/seeders/RemoveDocumentEmbederLibrarySeeder.php
deletion of document embeder h5p library
=> deletion of document embeder h5p library

app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php
CUR 4678 fetch activities of curriki user on deeplink activities tab
=> CUR 4678 fetch activities of curriki user on deeplink activities tab

app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php
Reverts ActiveLearningStudio/ActiveLearningStudio-API#1539
=> Revert "CUR 4678 fetch activities of curriki user on deeplink activities tab"

app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php
=> ogical error correction

app/Http/Requests/V1/GetTokenViaCode.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepository.php
=> tenant id to get from params

app/Http/Controllers/Api/V1/CurrikiGo/ExtractXAPIJSONController.php, database/migrations/2023_03_06_150851_change_xapi_class_id_datatype.php
log error if parsing fail for any statement due to missing class id
=> log error if parsing fail for any statement due to missing class id

app/Http/Requests/V1/GetUserProfileRequest.php
=> Dev to stage merge aqib

app/Http/Controllers/Api/V1/MicroSoftTeamController.php, app/Http/Requests/V1/GetUserProfileRequest.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepository.php
=> Develop to stage

app/Http/Controllers/Api/V1/CurrikiGo/ExtractXAPIJSONController.php, app/Http/Controllers/Api/V1/MicroSoftTeamController.php, app/Http/Requests/V1/GetTokenViaCode.php, app/Http/Requests/V1/GetUserProfileRequest.php, app/Http/Requests/V1/SubmitAssignmentMst.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepository.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepositoryInterface.php, app/Services/LearnerRecordStoreService.php, config/ms-team-configs.php, database/migrations/2023_03_06_150851_change_xapi_class_id_datatype.php, routes/api.php
Cherry pick mst stage to master 07 03 23
=> Cherry pick mst stage to master 07 03 23

app/Http/Controllers/Api/V1/MicroSoftTeamController.php, database/migrations/2023_03_06_150851_change_xapi_class_id_datatype.php
=> code api doc

database/migrations/2023_03_06_150851_change_xapi_class_id_datatype.php
=> Migration for xapi lrs

database/migrations/2023_03_07_151244_create_outcome_view.php
=> view creation

app/Http/Resources/V1/IndependentActivityResource.php, database/migrations/2023_03_09_134145_change_type_from_activities.php, database/seeders/ChangeTypeFromActivities.php
=> revert type column change

app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php
=> handled the crash

database/migrations/2023_03_14_074909_update_source_url_column_type_to_activities_table.php
CUR-4716 Update source url column type to activities table.
=> CUR-4716 Update source url column type to activities table.

app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php
Mst cherry pick to prod 15 03 23
=> Mst cherry pick to prod 15 03 23

app/Http/Controllers/Api/V1/MicroSoftTeamController.php, app/Http/Requests/V1/GetMsteamsSubmissionStatusRequest.php, app/Http/Requests/V1/GetTokenViaCode.php, app/Repositories/MicrosoftTeam/MicrosoftTeamRepository.php, routes/api.php
Backend changes to msteams integration
=> Msteams release

app/Repositories/Project/ProjectRepository.php
CUR-4752 add sentry alert for import projects
=> CUR-4752 add sentry alert for import projects

app/Http/Controllers/Api/V1/IndependentActivityController.php, app/Http/Controllers/Api/V1/ProjectController.php, app/Http/Requests/V1/OrganizationIndependentActivityRequest.php, app/Http/Requests/V1/OrganizationProjectRequest.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php, app/Repositories/Project/ProjectRepository.php
Added "Not Requested" filter for projects and activities.
=> CUR-4758: Not Requested filter in Admin Panel -Projects and Activities does not filter

app/Http/Controllers/Api/V1/IndependentActivityController.php, app/Http/Controllers/Api/V1/ProjectController.php, app/Http/Requests/V1/OrganizationIndependentActivityRequest.php, app/Http/Requests/V1/OrganizationProjectRequest.php, app/Repositories/IndependentActivity/IndependentActivityRepository.php, app/Repositories/Project/ProjectRepository.php
Added organization visibility type filter for projects and activities.
=> CUR-4757: Add Filter labels for Library Preference in Admin Panels

app/Notifications/ProjectImportNotification.php
Feature/cur 4749 update notification message for missing metadata
=> CUR-4749 update notification message

database/migrations/2023_04_11_073919_update_independent_activities_adv_search_functions_and_table.php
Integrated Niket script to resolve issue with activity search with single quote.
=> CUR-4727: Sentry issue: Search is not working if a keyword has single quote

app/Http/Resources/V1/IndependentActivityDetailResource.php, app/Models/IndependentActivity.php
Added to activity details the description, demo_activity_id and demo_video_id from activity_items based on h5pLib.
=> CUR-4763: Add to activity details the description, demo_activity_id and demo_video_id from activity_items

app/Http/Controllers/Api/V1/MicroSoftTeamController.php
Merged staging to develop and resolve conflicts.
=> Merged staging to develop and resolve conflicts.

app/Notifications/ExportUsersRequestProcessedNotification.php
Resolved the issue with "exportUsersRequest" data type in "ExportUsersRequestProcessedNotification".
=> CUR-4798: Demo Environment to be housed under Framework

app/Http/Controllers/Auth/AuthController.php, app/Models/InvitedGroupUser.php, app/Models/InvitedOrganizationUser.php, app/Models/InvitedTeamUser.php, app/Repositories/InvitedGroupUser/InvitedGroupUserRepository.php, app/Repositories/InvitedOrganizationUser/InvitedOrganizationUserRepository.php, app/Repositories/InvitedTeamUser/InvitedTeamUserRepository.php
Made the email lower case on google login and user invitation for org, group and team.
=> CUR-4924: Google Login with any other domain does not change login email address to lower case

app/Http/Controllers/Api/V1/IndependentActivityController.php
Removed backend permission for xapi download.
=> CUR-4570: Remove backend permission for xAPI download from staging too

app/CurrikiGo/Brightcove/Commands/Playlists/GetPlaylistCommand.php, app/CurrikiGo/Brightcove/Commands/Playlists/GetPlaylistCountCommand.php, app/CurrikiGo/Brightcove/Commands/Playlists/GetPlaylistVideosCommand.php, app/CurrikiGo/Brightcove/Commands/Playlists/GetPlaylistVideosCountCommand.php, app/CurrikiGo/Brightcove/Commands/Videos/GetVideoListByIdsCommand.php, app/CurrikiGo/Brightcove/Playlists/GetPlaylist.php, app/CurrikiGo/Brightcove/Playlists/GetPlaylistVideos.php, app/CurrikiGo/Brightcove/Videos/GetVideoListByIds.php, app/Http/Controllers/Api/V1/Integration/BrightcoveAPIClientController.php, app/Http/Requests/V1/Integration/BrightcoveAPI/BrightcoveAPIPlaylistVideosRequest.php, app/Http/Requests/V1/Integration/BrightcoveAPI/BrightcoveAPIRequest.php, app/Http/Requests/V1/Integration/BrightcoveAPI/BrightcoveAPIVideoByIdsRequest.php, routes/integrations.php
Implement brightcove playlists, playlist videos and video by ids api.
=> Implement brightcove playlists, playlist videos and video by ids api.

app/Http/Controllers/Api/V1/C2E/Publisher/PublisherController.php, app/Repositories/C2E/Publisher/PublisherRepository.php, app/Repositories/C2E/Publisher/PublisherRepositoryInterface.php, app/Services/C2E/Publisher/PublisherService.php, routes/c2e.php, storage/responses/c2e/publisher/publish-media.json
Updated publish endpoint, removed job, called publisher API directly and returned response.
Added the API to get independent activity media metadata for royalties. 
Refined the API to generate payload using the sample independent activity "The Scientific Revolution".
=> CEE-193: Generate payload integrate update

app/Services/C2E/Publisher/PublisherService.php
Updated URL in generated publish payload to shared URL as requesyted by Antonio.
=> CEE-193: Generate Payload

app/Services/C2E/Publisher/PublisherService.php
Updated publish payload generation script to include EPUBs as well.
=> CEE-218: Include Epub as a media owner charging royalties
