app/Repositories/Project/ProjectRepository.php

This PR should fix the issue of cascading is_public and indexing properties from the parent item (playlist or activities) when cloning.

CUR-508 - Fix for keeping activities and playlists private when cloning.

---

app/CurrikiGo/Canvas/Commands/GetCoursesCommand.php

We've changed the api end point for fetching courses to the one that is accessible using a teacher's access token.
The old one was only accessible to an admin level access token.

CUR-598 - Updated API endpoint for fetching own canvas courses.

---

app/Jobs/CloneActivity.php
app/Repositories/Activity/ActivityRepository.php
app/helpers.php

- Removed the CURL requests for activities cloning
- Replicate the H5P activity relational data
- Copy the content id of cloned activity to the new if exists

Removed curl requests for activities cloning

---

app/Http/Controllers/Api/V1/GoogleClassroomController.php
app/Http/Requests/V1/GCTurnInRequest.php
app/Models/GcClasswork.php
app/Providers/RepositoryServiceProvider.php
app/Repositories/GcClasswork/GcClassworkRepository.php
app/Repositories/GcClasswork/GcClassworkRepositoryInterface.php
app/Services/GoogleClassroom.php
app/Services/GoogleClassroomInterface.php
database/migrations/2020_10_27_070822_create_gc_classworks_table.php
routes/api.php

The following is included in the work:
CUR-635 - updated assignment urls, appended them with classwork id.
CUR-652 - saving classwork ids in database is done.
CUR-639 - Turn In an assignment functionality added.
Has a migration:
php artisan migrate --path=/database/migrations/2020_10_27_070822_create_gc_classworks_table.php

[CUR-635] Updated assignment links for Google classroom when publishing

---

app/Http/Controllers/Api/V1/CurrikiGo/OutcomeController.php
app/Services/LearnerRecordStoreService.php

Also, we're now showing skipped statements for the quizzes for which we didn't find any answered statements.

[CUR-764] - Added error handling for when the 'name' property is unavailable in XAPI statements

---

config/laravel-h5p.php

Enable Questionnaire for H5P Editor. 
Some libraries rely on an LRS to work and must be enabled.

Enable Questionnaire for H5P Editor

---

app/Http/Controllers/Api/V1/CurrikiGo/OutcomeController.php

The 'other' context property of the XAPI statements has been reordered, and updated, so have updated our logic accordingly.

[CUR-906] - Get the attempt IRI from the first index rather than the last

---

H5P/laravel-h5p/src/LaravelH5p/Helpers/H5pHelper.php
H5P/laravel-h5p/src/LaravelH5p/LaravelH5p.php
H5P/laravel-h5p/src/LaravelH5p/Repositories/LaravelH5pRepository.php
app/CurrikiGo/LRS/InteractionFactory.php
app/CurrikiGo/LRS/InteractionSummary.php
app/CurrikiGo/LRS/Interactions/ChoiceSummary.php
app/CurrikiGo/LRS/Interactions/FillInSummary.php
app/Http/Controllers/Api/V1/CurrikiGo/LmsController.php
app/Http/Controllers/Api/V1/CurrikiGo/OutcomeController.php
app/Http/Controllers/Api/V1/PlaylistController.php
app/Http/Requests/V1/SearchRequest.php
app/Http/Resources/V1/SearchResource.php
app/Models/Project.php
app/Repositories/Activity/ActivityRepository.php
app/Repositories/Playlist/PlaylistRepository.php
app/Services/LearnerRecordStoreConstantsInterface.php
app/Services/LearnerRecordStoreService.php
app/Services/LearnerRecordStoreServiceInterface.php
config/laravel-h5p.php
routes/api.php
storage/responses/outcome/student-result-summary.json
storage/responses/search/advance.json
storage/responses/search/dashboard.json

* [CUR-814] Canvas deeplinking integration (#214)
* canvas deeplinking integration updated
* CUR-788 - Fixed summary page for interacted/attempted quizzes. (#215)
* Fix issue with share playlist (#218)
* Added checks on to date to be same or after the from date. (#219)
Added the date in search response.
* enable Questionnaire for H5P Editor (#220)
Approved on Waqar's request.
* CUR-870 - Removed aggregate line-items from the summary page for complex activities. (#221)
* [CUR-814] LTI search changes (#223)
Implemented changes to LTI search
* [CUR-898] Adding student responses for non-scoring activities on the summary page. (#225)
* CUR-898 - Adding student responses for non-scoring interactions on the summary page.
* CUR-898 - Updating doc blocks.
* CUR-898 - Minor code fixes.
* Updated …

Deployment from staging to production.

---

app/Services/LearnerRecordStoreConstantsInterface.php
app/Services/LearnerRecordStoreService.php

Also, we updated IRI for skipped verb, as H5P uses http://adlnet.gov/expapi/verbs/ prefix.

[CUR-914] Added questionnaire skipped info on the summary page

---

database/seeds/DatabaseSeeder.php

Organization seeder was created after the Organization roles so there was an issue with the Foreign key constraint.

[CUR-1185] Issue with the Seeders Created For Organization

---

app/Http/Controllers/Api/V1/PlaylistController.php
app/Http/Resources/V1/PlaylistResource.php
app/Models/Playlist.php
app/Models/Project.php
app/Repositories/Playlist/PlaylistRepository.php
database/migrations/2021_11_19_102949_add_shared_to_playlists_table.php
routes/api.php

Adds the following routes:
// playlist share toggle
Route::get('projects/{project}/playlists/{playlist}/share', 'PlaylistController@share');
Route::get('projects/{project}/playlists/{playlist}/remove-share', 'PlaylistController@removeShare');
Route::get('projects/{project}/playlists/{playlist}/load-shared-playlist', 'PlaylistController@loadSharedPlaylist');
Route::get('projects/{project}/shared-playlists', 'PlaylistController@allSharedPlaylists');
Has one migration:
database/migrations/2021_11_19_102949_add_shared_to_playlists_table.php

[CUR-2312] Shared playlist apis

---

app/Http/Controllers/Api/V1/SearchController.php
app/Policies/OrganizationPolicy.php
app/Policies/ProjectPolicy.php
database/migrations/2022_02_01_080228_remove_search_project_export_import_organization_permission_types_table.php
database/seeds/OrganizationPermissionTypeRemovalSeeder.php

Removed the permissions for project:export, project:import, search:advance and search:dashboard.
Removed the authorization policy checks for search:advance and search:dashboard.
Replaced the authorization policy checks for project:export and project:import with organization:export-project and organization:import-project.

CUR-3133: Permissions related observations

---

database/migrations/2022_03_01_153314_add_organization_admin_brightcove_permission_type_seeder_with_force.php

Added “'--force' => true“ to new migration 
to run seeder "OrganizationAdminPanelBrightCovePermissionTypeSeeder" on server 
like stage that have prod env
Deleted the old migration "2022_01_26_114513_add_organization_admin_brightcove_permission_type_seeder.php"

CUR-3303: Added  “'--force' => true“ to BrightCove migration

---

app/Console/Kernel.php

Removed "SendDailyUsage" command from Kernel schedule on staging.

CUR-3560  Remove SendDailyUsage from Kernel

---

app/Console/Kernel.php

Removed "SendDailyUsage" command from Kernel schedule on master.

CUR-3560: Remove SendDailyUsage from Kernel

---

database/migrations/2022_05_20_564513_create_composite_unique_index_on_organization_role_types_table.php

1- check if there are duplicated role types that exist.
2- If yes, get all duplicated roles and delete existing and assign their associations to original role type IDs.
3- Remove all duplicated records once associations are deleted successfully.
4- Applied unique checks on role type name and organization_id in the database.

[CUR-3718] remove duplication records of role types and its associations

---

app/Http/Controllers/Api/V1/SuborganizationController.php
app/Repositories/ActivityItem/ActivityItemRepository.php
app/Repositories/Organization/OrganizationRepository.php
database/migrations/2022_06_22_100000_delete_questionnaire_from_layouts_table.php
database/migrations/2022_06_22_300000_assign_default_admin_role_permissions_to_suborganization_admins.php
database/migrations/2022_06_22_400000_update_activity_items_order.php
database/migrations/2022_06_22_500000_update_activity_layouts_descriptions.php
database/seeds/AssignDefaultAdminRolePermissionsToSuborganizationsAdminsSeeder.php
database/seeds/DeleteQuestionnaireFromLayoutsSeeder.php
database/seeds/UpdateActivityItemsOrderSeeder.php
database/seeds/UpdateActivityLayoutsDescriptionSeeder.php

- Managed demo activity and video IDs for the newly created organization.
- Assigned default admin permissions to all other organization admins.
- Deleted "Questionnaire" activity layout from layouts table.
- Removed commented update role policy that was commented for testing purposes.
- Have made all activity Items order # = 100
- Updated the Layout Descriptions. Got a description from the corresponding Activity item.
- Have fixed activity items ordering in query

[CUR-3833] managed demo activity and video IDs for newly created organziation for dev

---

app/Http/Requests/V1/IndependentActivityEditRequest.php

Resolved issue with updating independent activity library preference, made "data" param "nullable".

CUR-3908: Backend: Library Preference API Work

---

app/Http/Controllers/Api/V1/UserController.php
app/Http/Requests/V1/SuborganizationAddNewUser.php

If user email is already a part of any other organization and we want to add any new org, the password field will be now optional.

[CUR-3967] Ignore password for existing user to assign another organization

---

app/Repositories/IndependentActivity/IndependentActivityRepository.php

Resolved issue with independent search using negative query.

CUR-3971: Explore Library: Search results disappear when entering words that are not related to results in the "Does not contain" text box

---

database/migrations/2022_08_17_122428_run_independent_activity_view_edit_permissions_seeder.php
database/seeds/IndependentActivityPermissionsViewEditSeeder.php

Added seeder to assign view, edit permissions for independent activities for all user roles.

CUR-3997: Independent Activity Permissions Seeder

---

app/Http/Controllers/Api/V1/MicroSoftTeamController.php
app/Http/Requests/V1/MSTeamCreateAssignmentRequest.php
app/Jobs/PublishProject.php
app/Notifications/ProjectPublishNotification.php
app/Repositories/MicrosoftTeam/MicrosoftTeamRepository.php
app/Repositories/MicrosoftTeam/MicrosoftTeamRepositoryInterface.php

Feature/cur 4163 add abackground job publishing projectms team

CUR-4163-add background job for publishing

---

app/Http/Controllers/Api/V1/SuborganizationController.php
app/Http/Requests/V1/SuborganizationSave.php
app/Http/Requests/V1/SuborganizationUpdate.php
app/Http/Resources/V1/OrganizationResource.php
database/migrations/2022_09_29_112914_add_ms_team_visibility_fields_to_organizations_table.php
storage/responses/organization/suborganization.json

CUR-4179 - Add visibilty fields on ms team in admin panel

CUR-4179 - Add visibilty fields on ms team in admin panel

---

app/CurrikiGo/Smithsonian/Commands/Contents/GetContentListCommand.php
app/Http/Controllers/Api/V1/Integration/SmithsonianIOAAPIClientController.php

CUR-4199 update get content list api w.r.t search param.

CUR-4199 update get content list api w.r.t search param.

---

app/Console/Commands/MoveIndependentActivitiesToActivities.php
app/Repositories/IndependentActivity/IndependentActivityRepository.php

Created migration for moving independent activities data, H5P and thumb images and to activities.

CUR-4133: Implement 'independent' activities data can be segregated from 'activities' data
